### ISSUE TITLE
[Follow up to #7055] Content on "Highest Quality Playback" screen hard to read when device in "Dark Mode"

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#7769] opened 2023-07-21 19:20 UTC
### Description: 

Follow-up to #7055.

### Steps to Reproduce 
  1. Enable `Dark Mode` on the device
  2. Launch Brave > Three-dot menu > Settings
  3. Open `Media` under `DISPLAY` section
  4. Find `YOUTUBE` section > Tap `Highest Quality Playback` > Observe

### Actual result: 

When `Dark Mode` is ON, it's hard to read content on "Highest Quality Playback" screen.

|1Light Mode|Dark Mode|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/f3758d57-6e41-48c2-b59e-46a92bc862cb) | ![2](https://github.com/brave/brave-ios/assets/128532965/c433a904-1f5c-4715-909d-e73b290af31a) |

### Expected result:

Content on `Highest Quality Playback` screen must be easy to read.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Brave build: 1.56 (23.7.19.18)
BraveCore: 1.56.6 (115.0.5790.90)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? NA
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 

Device/OS: iPhone 14 [iOS 16.5.1]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment] 2023-07-21 19:32
Duplicate of https://github.com/brave/brave-ios/issues/7758

**Closed as not planned by kylehickinson** 2023-07-21 19:32 UTC
Labels: closed/duplicate
