### ISSUE TITLE
Icons incorrectly sized when accessing back button history

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#8214] opened 2023-10-10 18:55 UTC
### Description: 
Icon incorrectly sized when accessing back button history, impacting both iPhone and iPad. On iPad its sizing it correctly when loading url but refreshing will break it. 

![IMG_3575](https://github.com/brave/brave-ios/assets/17885425/92e6b3b9-d5be-4260-bf91-c2528b841003)

### Steps to Reproduce 
  1. Open some websites
  2. Long-press on back button 
  3. Observe icons in history

### Actual result: 
Example | Example
-|-
![IMG_3573](https://github.com/brave/brave-ios/assets/17885425/ce365678-d025-4cf5-bc3d-9dc88cf24ee2) | ![IMG_3574](https://github.com/brave/brave-ios/assets/17885425/c7dfbc4a-66c4-4cb8-a920-ca822374d955)

### Expected result:
Icon is sized correctly in the back button history

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

### Brave Version: 
`1.58 (23.10.6.14)`

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
iPhone, iPad

**Comment by iccub** [comment] 2023-10-11 18:03
Duplicate of https://github.com/brave/brave-ios/issues/8206

**Closed as not planned by iccub** 2023-10-11 18:03 UTC
Labels: closed/duplicate
