### ISSUE TITLE
Unit test "testAllShieldsOff()" is failing

### ISSUE THREAD

**Issue by noahamar** [brave/brave-ios#2443] opened 2020-04-03 19:55 UTC
The unit test "testAllShieldsOff()" in DomainTests.swift is failing after a clean pull of the development branch. Assertions fail on lines 82-84.

**Comment by iccub** [comment] 2020-04-06 13:39
Duplicate of https://github.com/brave/brave-ios/issues/2206

**Closed as completed by iccub** 2020-04-06 13:39 UTC
