### ISSUE TITLE
UI text indicates 'Private' when it isn't

### ISSUE THREAD

**Issue by marshray** [brave/brave-ios#2418] opened 2020-03-20 22:47 UTC
### Description: 
Apologies if I don't have the terminology right, but I think this called the "tab tray".

Given that a degree of "privacy by default" is an advertised feature of Brave, it seems entirely reasonable that anyone would interpret the underlined UI text "Private" as a positive indication of "Private Browsing" mode.

### Steps to Reproduce 
  1. View any page in non-Private-Browsing mode
  2. Tap square with [N] at bottom
  3. Observe that the text displayed at the bottom is (screenshot attached)
**Private**    **+**   **Done**

  4. Tap on +
  5. Observe that tab is not, in fact, Private

**Actual result:**
![image](https://user-images.githubusercontent.com/1220724/77210571-925b2a00-6abe-11ea-80c9-e44c53a54fbf.png)

**Expected result:**
The text explicitly states 'Private', so I would expect anything opened from there to be in Private Browsing mode.

**Reproduces how often:**
Every time.

**Brave Version:** 
1.14.3 (20.02.01.06)

**Device details:** 
iPhone 6+
iOS 12.4.5

### Additional Information
iOS Safari has this bug too.

**Comment by srirambv** [comment] 2020-03-23 13:12
That is just an switch to Private browsing. If you tap that then the browser goes into private mode until then its normal browsing mode. Not a bug. Closing the issue as expected as per current design. Can continue conversation here for design aspects and reopen if required

cc: @jamesmudgett @brave/design

**Closed as completed by srirambv** 2020-03-23 13:12 UTC
Labels: closed/not-actionable
