### ISSUE TITLE
Adding favorite without http/https prefix doesn't load favicon even after visiting site

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#971] opened 2019-03-14 13:24 UTC
### Description: 
Found while testing https://github.com/brave/brave-ios/issues/739

Adding favorite without http/https prefix doesn't load the site favicon even after you visit the site.

### Steps to Reproduce 
  1. Clean profile on 1.9 (19.3.9.1)
  2. Edit a favorite and add title as `Github` and replace url with `github.com` (no favicon)
  3. Load the edited favorite, site loads.
  4. Open a new tab.

**Actual result:** 
Edited favorite doesn't have a favicon (lower left one)
![Image from iOS](https://user-images.githubusercontent.com/28145373/54360191-b9288a00-463a-11e9-8c2f-6d0422a88706.png)

**Expected result:**
Favicon would load after site was visited

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.9 (19.3.9.1)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? n/a
- did you check in Safari/Firefox (WkWebView-based browsers)? no

**Comment by btlechowski** [comment] 2019-03-14 21:36
Reproduced with 1.9 (19.3.9.1) on iPhone SE

**Comment by GeetaSarvadnya** [comment] 2019-03-18 12:19
Similar to https://github.com/brave/brave-ios/issues/572

**Comment by srirambv** [comment] 2019-03-18 13:54
Closing as dupe of #572

**Closed as completed by srirambv** 2019-03-18 13:54 UTC
Labels: closed/duplicate
