### ISSUE TITLE
Background playback doesn't stop

### ISSUE THREAD

**Issue by mikel2000** [brave/brave-ios#5579] opened 2022-06-23 18:01 UTC
### Description: 
When background playback is enabled in preferences and the tab with the playback source is closed, playback doesn't stop. The only way to stop playback is closing the browser.

### Steps to Reproduce 
  1. Enable background playback in preferences
  2. Go to youtube and start a video
  3. Open a new tab
  4. Close the tab where the youtube video was started
  5. Playback doesn't stop

**Expected result:**
When the tab with the playback source is closed, playback should stop. Currently the only way to stop playback is closing the browser.

**Reproduces how often:** Always

**Brave Version:** 1.39.1 (22.6.10.17)

**Device details:** iPhone SE 2020, iOS 15.4.1

**Comment by iccub** [comment] 2022-06-24 13:54
Thanks for this report, we fixed it recently but looks like it's back, going to look into this

**Comment by mikel2000** [comment] 2022-06-24 18:26
I'm no longer able to reproduce it... So, it seems, that there need to be more conditions met. If I find out, which conditions these are, I will update the list of steps to reproduce.

**Comment by iccub** [comment] 2022-06-24 20:44
We are able to reproduce, should be fixed in 1.40 which lands next week. Thanks for bringing this to our attention

**Closed as completed** 2022-06-24 23:44 UTC
Labels: bug, QA Pass - iPhone X, QA/Yes, QA Pass - iPhone, QA Pass - iPad

**Comment by Uni-verse** [comment] 2022-06-27 23:31
Verified using 1.40 (22.6.27.15)

Devices:
iPhone 12 | iOS 15.5
iPhone X | iOS 14.4.2
iPad | iPadOS 15.5

- Verified playback stops when closing tab using STR in https://github.com/brave/brave-ios/issues/5579#issue-1282758618
