### ISSUE TITLE
bookmark hanger remains open after Open All Bookmarks in Folder 

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#822] opened 2019-01-29 17:10 UTC
### Description: 
Found while testing https://github.com/brave/brave-ios/issues/665

When opening all bookmarks in a folder, the bookmark hanger remains open. Hanger should close after selecting `Open All (x)`.

### Steps to Reproduce 
  1. Create a bookmark folder
  2. Put at least two bookmarks in the folder
  3. Long press on the folder
  4. Select `Open All (x)`
  5. Bookmarks open in new tabs

**Actual result:** 
Bookmarks hanger remains open

**Expected result:**
Bookmarks hanger should close

**Reproduces how often:** 
easily

**Brave Version:** 
1.8 (19.01.25.19)

**Device details:** 
iPad 5th Gen

**Website problems only:**
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment] 2019-02-08 13:28
This is an issue on iPhone as well.

**Comment by srirambv** [comment] 2019-02-08 13:29
Moving to 1.9 as this isn't a critical bug

**Comment by GeetaSarvadnya** [comment] 2019-03-27 09:30
The issue is reproducible on iPhone 8 with the brave version 1.8

**Closed as completed** 2019-04-10 08:36 UTC
Labels: bug, good first issue, priority/P3, QA/Yes, release-notes/exclude

**Comment by LaurenWags** [comment] 2019-07-12 19:16
* Verified with iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.12.14) - issue remains. Logged #1246 for follow up.
* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`
