### ISSUE TITLE
Pull to refresh page similar to Chrome for iOS

### ISSUE THREAD

**Issue by gh0sti** [brave/brave-ios#2851] opened 2020-08-31 18:03 UTC
Pull to refresh option similar to how Chrome for iOS is able to reload webpages

**Comment by kylehickinson** [comment] 2020-08-31 18:08
Hi @gh0sti, thanks for the feature request! This has actually already been requested so I'm going to close this as a duplicate and give a +1 on the original ticket

**Comment by kylehickinson** [comment] 2020-08-31 18:08
Duplicate of #916

**Closed as completed by kylehickinson** 2020-08-31 18:08 UTC
Labels: closed/duplicate
