### ISSUE TITLE
Do not block googleadservices in 1p context

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#899] opened 2019-02-14 02:37 UTC
### Steps to Reproduce 
  1. Open google.com
  2. Search for Ledger Nano S
  3. Click the sponsored ads - blocked

**Actual result:** 
Blocked

**Expected result:**
Should not be blocked

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.7.4

**Comment by kylehickinson** [comment] 2019-02-14 04:43
Duplicate of #675

**Closed as completed** 2019-02-14 05:40 UTC
Labels: closed/duplicate
