### ISSUE TITLE
Feature Request: Add disable all sources option in Brave today

### ISSUE THREAD

**Issue by tankmohit** [brave/brave-ios#3539] opened 2021-04-17 20:47 UTC
Brave today is a great addition to the browser. But whenever brave is installed on new devices, it enables default sources in Brave today. 

This adds many steps if you need to enable only couple of news feeds, by going through each category and disable unnecessary sources.

An option for disabling all sources with one click would be great feature and make this process more convenient for those who are not interested in default selection.

**Comment by mattmcalister** [comment] 2022-03-08 12:19
Duplicate of https://github.com/brave/brave-browser/issues/13362

**Comment by kylehickinson** [comment] 2023-01-17 21:29
This can be closed now as the only thing followed on initial setup in the revamp is the "Top Sources" channel which be easily unfollowed

**Closed as not planned by kylehickinson** 2023-01-17 21:29 UTC
Labels: closed/wontfix
