### ISSUE TITLE
Toolbar bug when changing orientation while a video is playing

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6324] opened 2022-11-03 23:15 UTC
### Description: 
More info here https://community.brave.com/t/ios-ui-subtle-tab-bar-glitch/436705

### Steps to Reproduce 
1. Play any video on full screen (Portrait orientation).
2. Change orientation to Landscape.
3. Go back to Portrait.
4. Close full screen by swipe down gesture.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment] 2022-11-23 19:08
Let's retest and close, maybe its fixed

**Comment by kylehickinson** [comment] 2022-11-23 19:58
Still can reproduce so not fixed

**Comment by iccub** [comment] 2022-11-23 20:00
thanks, let's fix it as a weekly sometime in the future

**Comment by iccub** [comment] 2022-12-13 00:14
Reopening, this has caused another bug https://github.com/brave/brave-ios/issues/6623

**Comment by kylehickinson** [comment] 2023-11-07 15:22
Duplicate of https://github.com/brave/brave-ios/issues/8009

**Closed as not planned by kylehickinson** 2023-11-07 15:22 UTC
Labels: closed/duplicate
