### ISSUE TITLE
Unable to open settings on youtube properly

### ISSUE THREAD

**Issue by emmohac** [brave/brave-ios#2887] opened 2020-09-20 07:39 UTC
### Description: 
I am unable to use open the settings of youtube on brave browser on iPad. It keeps showing the circle rolling as seen in the picture below.

### Steps to Reproduce 
  1. Open brave browser on iPad
  2. Go to youtube.com
  3. Touch on the settings (3 vertical dots) as showed in the picture below

**Actual result:** 
![brave_ipad_youtube_error](https://user-images.githubusercontent.com/29102852/93706160-6a359d80-fad8-11ea-9bb6-65628ab0310c.jpg)

**Expected result:**
The settings to display a list of options such as being able to choose themes or changing languages, etc.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
v1.19.2 (20.08.05.18)

**Device details:** 
Ipad Air 3rd gen (iOS 14)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
I did turn on request desktop site in brave browser settings.

**Comment by iccub** [comment] 2020-10-05 14:41
@kylehickinson is this a duplicate of https://github.com/brave/brave-ios/issues/2810?

**Comment by kylehickinson** [comment] 2020-10-05 14:42
It may be, but I'm not sure, would need to verify

**Comment by iccub** [comment] 2020-10-05 18:30
@brave/legacy_qa can you verify that? there's a chance this has been fixed in 1.20,
1 iPad 1 iPhone should be enough

**Comment by kjozwiak** [comment] 2020-10-05 21:36
> @brave/legacy_qa can you verify that? there's a chance this has been fixed in 1.20,
> 1 iPad 1 iPhone should be enough

@iccub looks fixed on both `1.20 (20.09.11.20)` & `1.21 (20.10.02.20)` as per the following:

`1.20 (20.09.11.20) iPhone 11 iOS 14` | `1.20 (20.09.11.20) iPad Air (3rd Gen) iOS 14` |
--------------------------| ----------------------------------|
| ![D03208B3-D09F-4D17-B20C-8564F64BD88A](https://user-images.githubusercontent.com/2602313/95134029-2e354600-0730-11eb-9ad0-649ed8823413.PNG) | ![IMG_EACD4819E52F-1](https://user-images.githubusercontent.com/2602313/95134542-0e525200-0731-11eb-9630-421427f8bee9.jpeg) |


`1.21 (20.10.02.20) iPhone 11 iOS 14` | `1.21 (20.10.02.20) iPad Air (3rd Gen) iOS 14` |
--------------------------| ----------------------------------|
| ![A1BC0892-35DF-48AE-B2BA-8EC0E95A4A6A](https://user-images.githubusercontent.com/2602313/95133999-283f6500-0730-11eb-943c-bab21f6335bb.PNG) | ![IMG_0161](https://user-images.githubusercontent.com/2602313/95134378-c92e2000-0730-11eb-9ceb-1ed88afd1c25.PNG) |

**Comment by iccub** [comment] 2020-10-05 21:38
Thanks for checking it. This is fixed in 1.20, closing as a duplicate

**Closed as completed** 2020-10-05 21:39 UTC
Labels: closed/duplicate

**Comment by emmohac** [comment] 2020-10-06 00:54
@iccub @kylehickinson @kjozwiak It works as expected after updating to 1.20. Thank you, guys.
