### ISSUE TITLE
Bottom bar disappears when clearing recent searches

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#6992] opened 2023-02-22 18:51 UTC
### Description: 
Bottom bar disappears when clearing recent searches

### Steps to Reproduce 
  1. Install 1.48 
  2. Perform some searches
  3. Tap on URL bar, enable recent searches
  4. Now clear recent searches
  5. Observe

### Actual result: 
Search bar disappears

https://user-images.githubusercontent.com/17885425/220729259-a3c71f73-6575-497c-b5ad-b448336d9b25.MP4

### Expected result:
Search bar should not disappear

### Reproduces how often: [Easily reproduced, Intermittent Issue]
ALways

### Brave Version: 
`1.48 (23.2.22.16)`

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
`iPhone 12`, `iOS 16.1`

**Comment by kylehickinson** [comment] 2023-02-22 18:53
Duplicate of https://github.com/brave/brave-browser/issues/37066

**Closed as not planned by kylehickinson** 2023-02-22 18:53 UTC
Labels: closed/duplicate
