### ISSUE TITLE
Adblock/Cosmetic filters crash

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6254] opened 2022-10-26 16:35 UTC
### Steps to Reproduce 
No way to reproduce found so far.

**Actual result:** 
Crash

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment] 2023-01-26 16:28
to retest

**Comment by antonok-edm** [comment] 2023-02-10 21:59
This is due to unsafe access of the adblock engine on multiple threads.

Context - https://bravesoftware.slack.com/archives/C7VLGSR55/p1676043650091859

**Comment by cuba** [comment] 2023-02-12 10:17
My latest changes here moves all access to the engine to a serial queue: https://github.com/brave/brave-ios/pull/6857. Meaning we will not be using multiple threads anymore after this change. I did performance and script injection tests and everything works well.

**Comment by kjozwiak** [comment] 2023-02-21 22:53
@iccub @kylehickinson moved this into `1.48` as https://github.com/brave/brave-core/pull/17283 was uplifted into `1.48`. Once we get new TF builds with the above changes, we can close this off. CCing @Uni-verse please keep an eye on performance in general when using the next RC with the above and when running through the above verification.

**Comment by Uni-verse** [comment] 2023-02-25 02:46
Not reproduced on `1.48 (23.2.24.14)` & `1.48 (23.2.23.23)` release channel builds on the following device(s):

iPhone 12, iOS 16.1
iPhone XR, IOS 15.5
iPhone X, iOS 14.4.2
iPad, iPadOS 15.6.1

**Comment by cuba** [comment] 2023-03-25 13:03
Re-opened because it was reverted

**Closed as completed** 2023-04-01 10:43 UTC
Labels: bug, QA Pass - iPhone X, QA/Yes, regression, crash, release-notes/include, QA Pass - iPhone, QA Pass - iPad, feature/shields/adblock
