### ISSUE TITLE
Add option for custom adblocking lists

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3714] opened 2021-05-24 19:15 UTC
### Description: 
A iOS reviewer requested that we add support for custom adblocking lists
Desktop is gaining this functionality so perhaps iOS could leverage some of this work

cc @pes10k

**Comment by iccub** [comment] 2022-08-15 10:07
duplicate of https://github.com/brave/brave-ios/issues/3714

**Closed as not planned by iccub** 2022-08-15 10:07 UTC
Labels: closed/duplicate

**Comment by davidcollini** [comment] 2022-11-10 14:27
This should be re-opened as it can't be a duplicate of itself
