### ISSUE TITLE
Crash on translate.google.de

### ISSUE THREAD

**Issue by mikel2000** [brave/brave-ios#5281] opened 2022-04-22 16:32 UTC
### Description: 
Brave crashes on translate.google.de when the red magnifier is selected during text input.

### Steps to Reproduce 
  1. Open translate.google.de
  2. Tap on the text input
  3. Press on the red magnifier which is shown below (see screenshot below)
  4. Braves crashes every time

**Brave Version:** 1.37 (22.4.6.8)

**Device details:** iPhone SE 2020, iOS 15.4.1

### Additional Information
The problem occurs with shields on/off.
The red magnifier is not enabled on translate.google.com.

![brave_crash_google_translate](https://user-images.githubusercontent.com/7446969/164755725-a735934e-b1ed-4f67-9e67-1c5ca5e8fe43.jpg)

**Comment by Brandon-T** [comment] 2022-04-25 13:38
Hi I am seeing the following image when tapping on the search icon: 
![image](https://user-images.githubusercontent.com/1530031/165100382-44f88c0b-c865-4f3d-af90-7c20755fc0d0.png)

This should already be fixed by: https://github.com/brave/brave-ios/issues/5243
CC @soner-yuksel

**Comment by soner-yuksel** [comment] 2022-04-25 14:26
Yes it will be fixed in 1.38. Also did a sanity check everything is fine with 1.38.

**Comment by kylehickinson** [comment] 2022-04-25 14:50
Duplicate of https://github.com/brave/brave-ios/issues/5243

**Closed as completed by kylehickinson** 2022-04-25 14:50 UTC
Labels: closed/duplicate
