### ISSUE TITLE
Support "Open in Place" for the Downloads folder

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#225] opened 2018-09-04 15:23 UTC
Support "Open in Place" for the Downloads folder so that users can open downloaded content directly on their device

**Comment by jhreis** [comment] 2019-03-27 15:14
@tmancey Can you please provide a bit more info about this ticket, and if it is a duplicate of #206 ?

**Comment by tmancey** [comment] 2019-03-28 21:58
@jhreis This is not the same, for "open in place" see https://developer.apple.com/document-based-apps/ for when users download PDFs etc.

**Comment by kylehickinson** [comment] 2019-11-16 02:34
Is this ticket still valid? Is #1467 a duplicate of this?

**Comment by tmancey** [comment] 2019-11-16 08:59
@kylehickinson Open in place would allow users to open files directly, i.e. preview from the browser

**Comment by kylehickinson** [comment] 2019-11-16 14:15
Is there a reason why we'd want to do this? I think the quick look preview would be good enough, and let the user open the document in the proper app outside of Brave.

**Comment by kylehickinson** [comment] 2019-11-18 17:42
Turns out the `Open In` (from [UIDocumentInteractionController](https://developer.apple.com/documentation/uikit/uidocumentinteractioncontroller)) shows pretty much the same thing as the activity controller now… without the preview. Will probably stick with the QuickLook previewer instead

**Comment by kylehickinson** [comment] 2019-11-18 19:02
Closing for now as we merged QuickLook previewing and closed #1467

**Closed as completed by kylehickinson** 2019-11-18 19:02 UTC
Labels: enhancement, blocked: needs info, QA/Yes, release-notes/include
