### ISSUE TITLE
Address bar - Text selection icons at wrong position 

### ISSUE THREAD

**Issue by cooperbang** [brave/brave-ios#8511] opened 2023-12-01 07:05 UTC
### Description: 
When opening long URLs the text selection icons are at the wrong position.

### Steps to Reproduce 
  1. Open a longer URL like 
https://support.apple.com/en-us/HT213781 or 
https://www.businesstraveller.com/tried-and-tested/hotel-molitor-paris-m-gallery/
  2. Tap at address bar

### Actual result: 
Text selection icons are at wrong position and sometimes can´t be moved.

Here the selection icon is placed after https://
![1](https://github.com/brave/brave-ios/assets/75366896/52d72bb1-7f04-4557-bfff-146675dea590)

And here the selection icon is placed above the "Abbrechen" button
![2](https://github.com/brave/brave-ios/assets/75366896/a29ed7ec-bb5b-4894-81ba-5162b0b6e8dd)

Additionally, it seems a little strange that the magnifying glass can be moved across the "Abbrechen" button, when trying to move the text selector icon.
![3](https://github.com/brave/brave-ios/assets/75366896/06f99fa5-10c1-49f6-a2d7-2c38fcf1da11)

### Expected result:
Text selection icons shoud be placed at the beginning  and the end of the visible address bar area.

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

### Brave Version:
1.60.122 (119.0.6045.163)

### Device details:
iPhone 11 (iOS 17.1.2)

### Website problems only:
Did you check with Brave Shields down? 
Yes

Did you check in Safari/Firefox (WkWebView-based browsers)? 
Yes

**Comment by kylehickinson** [comment] 2023-12-01 15:03
Duplicate of https://github.com/brave/brave-ios/issues/8374

**Closed as not planned by kylehickinson** 2023-12-01 15:03 UTC
Labels: closed/duplicate
