### ISSUE TITLE
Unable to click on dropdown in portfolio

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#6273] opened 2022-10-27 20:02 UTC
### Description: 
Unable to click on dropdown in portfolio

### Steps to Reproduce 
  1. Add a bunch of accounts
  2. Click on network dropdown 
  3. Doesn't show network dropdown

**Actual result:** 

https://user-images.githubusercontent.com/17010094/198386910-af910305-786e-4ef7-85c1-80cd02e2c807.MP4

**Expected result:**
Should be able to open network dropdown

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.45 (22.10.25.19)

**Device details:** 
iPad Pro (iOS 16.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by StephenHeaps** [comment] 2022-12-13 19:21
Duplicate of https://github.com/brave/brave-browser/issues/36774

**Closed as not planned by StephenHeaps** 2022-12-13 19:21 UTC
Labels: bug, closed/duplicate, release-notes/exclude, Epic: Brave Wallet, iOS 16
