### ISSUE TITLE
borsen.dk website is NOT loading 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#1061] opened 2019-04-22 07:08 UTC
### Description: 
borsen.dk website is NOT loading 

### Steps to Reproduce 
  1. Open borsen.dk
  2. Tap Enter
  

**Actual result:** 

borsen.dk website doesn't load keeps loading the page and never loads the page even after the shield settings change

**Expected result:**
borsen.dk website should load

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
1.9.1

**Device details:** 
iPhone 8

**Website problems only:**
- did you check with Brave Shields down? Yes
- did you check in Safari/Firefox (WkWebView-based browsers)? Yes - Same issue exists in FF

### Additional Information 
The issue is reported by the community

https://community.brave.com/t/site-not-showing-loading/55340

**Comment by cndouglas** [comment] 2019-04-22 23:30
## Problem
`borsen.dk` initially redirects to an ad domain (`ad1.emediate.dk`). The ad domain is blocked by the adblocker, which prevents the redirect from occurring. Disabling shields does not help because it only disables shields for `borsen.dk` itself, not the intermediate ad domain.

## Workaround (general case)
1. Disable the global ad & tracking setting.
After the adblocker is disabled, the ad domain loads and is allowed to set a cookie. Once this cookie is set, borsen.dk no longer redirects through the ad domain.
2. Enable the global ad & tracking setting again.
The webpage will continue to load fine, unless cookies are cleared.

### Screen capture
![](https://user-images.githubusercontent.com/19424103/56538432-a43bf200-6528-11e9-9b7e-654f5bd6b38a.gif)

## Workaround (specific case)
In this particular case, the final redirection uses the URL `borsen.dk/#eas_redir=true`. Navigating to that URL sets the cookie directly, without the ad domain redirection.

**Comment by kylehickinson** [comment] 2019-04-23 00:22
Looks like we need to determine the specific rule which is causing the block and then force it to third-party only. I'll determine the failing rule tomorrow morning to fix the issue with `borsen.dk`

**Comment by kylehickinson** [comment] 2019-04-23 17:41
Rule fixed in [ab2cb#fd236ad](https://github.com/brave/ab2cb/commit/fd236ad2612754cd053316e19a8f6bb992492838).  Will update content blockers when the filters are re-deployed ([devops#900](https://github.com/brave/devops/issues/900))

**Closed as completed** 2019-06-21 14:41 UTC
Labels: bug, QA/Yes, release-notes/include, Epic: Webcompat

**Comment by srirambv** [comment] 2019-07-10 13:35
Page load is still quite slow. Page load completes successfully however it took almost a min for me to load the page fully. Navigating to other pages while the homepage is being loaded causes the new page load to go even slower.

Tested on 1.10(19.07.08.19). @kylehickinson could you confirm if this is acceptable behaviour for the page?

**Comment by kylehickinson** [comment] 2019-07-10 13:40
@srirambv Tested it on 1.10 (19.07.08.19) default config and didn't see any slowness on my side. 

Either way though, I don't think _slowness_ could be something caused by this change, which was simply letting it load in the first place.

**Comment by srirambv** [comment] 2019-07-10 13:50
* Verification passed on iPhone 7+ (iOS 12.3.1) running 1.10 (19.07.08.19)
* Verification **PASSED** on `iPad Mini 4 running iOS 12.3.1` using `1.10 (19.07.10.17)`
