### ISSUE TITLE
Brave is responding to and opening firefox:// URL schemes

### ISSUE THREAD

**Issue by justindarc** [brave/brave-ios#929] opened 2019-02-28 18:30 UTC
### Description: 
Brave is responding to and opening `firefox://` URL schemes.

### Steps to Reproduce 
  1. Install Firefox for iOS
  2. Install Brave
  3. Go to Firefox's "Today" widget and select "New Tab" or "New Private Tab"
  4. Get prompted to "Open in 'Brave'"

**Actual result:** 
![img_0588](https://user-images.githubusercontent.com/207595/53589233-e0705900-3b5c-11e9-9d93-6340db9c8d3b.PNG)

**Expected result:**
Firefox for iOS should open automatically

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
Latest

**Device details:** 
n/a

**Comment by kylehickinson** [comment] 2019-02-28 18:41
Duplicate of #890

**Closed as completed by kylehickinson** 2019-02-28 18:41 UTC
Labels: closed/duplicate
