### ISSUE TITLE
Favourites flash when long pressed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2677] opened 2020-06-29 16:45 UTC
### Description: 
Favourites flash when long pressed

### Steps to Reproduce 
  1. Install 1.18 RC build
  2. Long press on favourites
  3. Favourites flicker before context menu opens

**Actual result:** 

**Expected result:**
No flicker

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.18(20.06.26.17)

**Device details:** 
iPad and iPhone running iOS 13.x 

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
Issue not reproduced on iOS 12

**Comment by kylehickinson** [comment] 2020-06-29 17:16
Could not reproduce in any simulator build (13.5, with and without accessibility settings) or device build (14 beta 1). Don't believe I ever saw this on latest iOS 13 before I updated to 14 beta. Will need further investigation as to why this happens

**Comment by kylehickinson** [comment] 2020-06-29 17:18
Closed as dupe was opened #2678

**Closed as completed by kylehickinson** 2020-06-29 17:18 UTC
Labels: closed/duplicate
