### ISSUE TITLE
verified, non-KYC'd publishers shown as not verified in 1.22

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#3110] opened 2020-12-04 15:28 UTC
### Description: 
Publishers who are connected (verified with Brave but not KYC'd with Uphold) are not shown as verified in 1.22 and not included in Auto Contribute.

### Steps to Reproduce 
  1. Install 1.21, enable Rewards icon, set staging env
  2. Relaunch
  3. Enable Rewards
  4. Claim UGP grant
  5. Visit a connected publisher on staging (ex. DDG). Confirm publisher shows as verified on panel.
  6. Wait minimum amount of time to see DDG get added to AC list
  7. Open AC settings, toggle off "Show non-verified sites in list"
  8. Confirm DDG remains in AC list.
  9. Upgrade to 1.22
  10. Visit DDG and open panel --> Shows as not verified
  11. Wait minimum amount of time to be added to AC --> View AC list in QA settings, DDG is not added

Found with upgrade, also reproduces on clean profile. 

**Actual result:** 
![IMG_446BDED0030E-1](https://user-images.githubusercontent.com/28145373/101181583-0de41380-361b-11eb-8501-27bcded93dfa.jpeg)

**Expected result:**
Panel should reflect that DDG is verified and will be included in AC

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.22 (20.12.2.1) 

**Device details:** 
iPad mini with iOS13

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc @anthonypkeane @kjozwiak @kylehickinson @srirambv

**Comment by kylehickinson** [comment] 2020-12-04 18:42
> Visit DDG and open panel --> Shows as not verified

Right now we are not showing `connected` publishers as verified, fixing this.

> Wait minimum amount of time to be added to AC --> View AC list in QA settings, DDG is not added

So 2 things to note on this:
1. On upgrade your old profile is purged, therefore publist and AC activity is reset.
2. Showing the debug menu or going to settings _does not_ count as navigating the page, therefore isn't recorded in AC. Navigating to the Rewards panel _does_ however count as leaving the page (since we need to update the visible panel data). So to correctly ensure DDG is added to the internals list going forward from 1.22 you must either wait the required time then tap on the web page to navigate it somewhere else _or_ open the Rewards panel momentarily.

I tested and DDG was indeed added to the AC table after I viewed the panel:

![image](https://user-images.githubusercontent.com/529104/101201953-886e5c80-3636-11eb-9954-399258661bc0.png)

**Comment by kylehickinson** [comment] 2020-12-04 18:43
Also marking this as a regression since previous versions showed connected publishers correctly

**Comment by LaurenWags** [comment] 2020-12-04 18:51
Thanks for clarifications @kylehickinson

**Closed as completed** 2020-12-04 19:37 UTC
Labels: bug, QA/Yes, regression, release-notes/exclude, QA Pass - iPhone, QA Pass - iPad, Epic: Rewards

**Comment by LaurenWags** [comment] 2020-12-11 17:38
Verification passed on iPad mini with iOS 13 running 1.22.1 (20.12.10.22) using staging env:

<details>
<summary>Confirmed verified, non-KYC'd (connected) publishers show as included in support</summary>

![IMG_1B9BB6420EC7-1](https://user-images.githubusercontent.com/28145373/101935622-5c5e5880-3bad-11eb-99df-3c227c2d05be.jpeg)

</details>

<details>
<summary>Confirmed verified, KYC'd publishers show as included in support</summary>

![IMG_E6C8B24DEF69-1](https://user-images.githubusercontent.com/28145373/101935646-61230c80-3bad-11eb-8b19-2356bf310e96.jpeg)

</details>

<details>
<summary>Confirmed non-verified publishers do not show as included in support</summary>

![IMG_252B2E58F6F7-1](https://user-images.githubusercontent.com/28145373/101935818-a21b2100-3bad-11eb-9e0f-f97429f294ea.jpeg)

</details>

<details>
<summary>Confirmed verified, non-KYC'd (connected) and verified, KYC'd publishers are listed in auto-contribute</summary>

![IMG_D2F7F20CF51B-1](https://user-images.githubusercontent.com/28145373/101935860-b4955a80-3bad-11eb-9b57-3b0d06277cdf.jpeg)

</details>

-------

Verification **PASSED** on `iPhone 11` running `iOS 14.2` using `1.22.1 (20.12.10.22)` via `staging`:

<details>
<summary>Confirmed verified, non-KYC'd (connected) publishers show as included in support</summary>

![image](https://user-images.githubusercontent.com/2602313/102300528-1f82c080-3f23-11eb-804a-e978b68712ab.png)

</details>

<details>
<summary>Confirmed verified, KYC'd publishers show as included in support</summary>

![image](https://user-images.githubusercontent.com/2602313/102300551-2f020980-3f23-11eb-9e00-316175585074.png)

</details>

<details>
<summary>Confirmed non-verified publishers do not show as included in support</summary>

![image](https://user-images.githubusercontent.com/2602313/102300589-3cb78f00-3f23-11eb-9ea6-fccb7ee16fd5.png)

</details>

<details>
<summary>Confirmed verified, non-KYC'd (connected) and verified, KYC'd publishers are listed in auto-contribute</summary>

![IMG_3513](https://user-images.githubusercontent.com/2602313/102300602-44773380-3f23-11eb-80f3-6a33708737fc.png)

</details>

-------

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.22.1 (20.12.10.22)` via `staging`:

<details>
<summary>Confirmed verified, non-KYC'd (connected) publishers show as included in support</summary>

![image](https://user-images.githubusercontent.com/2602313/102301358-9e2c2d80-3f24-11eb-8583-c65b806072be.png)

</details>

<details>
<summary>Confirmed verified, KYC'd publishers show as included in support</summary>

![image](https://user-images.githubusercontent.com/2602313/102301374-a71cff00-3f24-11eb-9587-0bdfb422accd.png)

</details>

<details>
<summary>Confirmed non-verified publishers do not show as included in support</summary>

![image](https://user-images.githubusercontent.com/2602313/102301389-b00dd080-3f24-11eb-9f37-3fe0de67347c.png)

</details>

<details>
<summary>Confirmed verified, non-KYC'd (connected) and verified, KYC'd publishers are listed in auto-contribute</summary>

![IMG_0087](https://user-images.githubusercontent.com/2602313/102301404-b8660b80-3f24-11eb-9b60-b1d36a54b7a1.png)

</details>
