### ISSUE TITLE
Restoring VPN doesn't work

### ISSUE THREAD

**Issue by chkk525** [brave/brave-ios#2748] opened 2020-07-29 00:24 UTC
![IMG_3200](https://user-images.githubusercontent.com/3054915/88742312-dfda5880-d17c-11ea-9d79-d9eb66fe0e57.PNG)

### Steps to Reproduce 
  1. Open the setting menu and select Brave VPN
  2. Tap "Restore"
  3. The screen keeps loading forever 

**Actual result:** 
![IMG_3200](https://user-images.githubusercontent.com/3054915/88742327-e9fc5700-d17c-11ea-8711-43b86ddd32c4.PNG)

**Expected result:**
- Should start restoring process

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
- Every time, even after killing and re-launching the app

**Brave Version:** 
- 1.9

**Device details:** 
- iPhone X(iOS 13.5.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by bsclifton** [comment] 2020-08-31 16:41
@iccub was there a fix for this one? or still needs to be investigated?

**Comment by iccub** [comment] 2020-08-31 16:48
still under investigation, no regular user has reported this yet

**Comment by chkk525** [comment] 2020-09-03 02:50
I couldn't reproduce this now, so it might be my device or icloud account problem.

**Comment by iccub** [comment] 2020-12-04 14:07
Closing for now, it can be caused by Apple servers, it's not easy to reproduce and I don't see users posting about having this problem.

**Closed as completed by iccub** 2020-12-04 14:07 UTC
Labels: closed/works-for-me
