### ISSUE TITLE
Brave News opt-in modal/card missing images/animation on new profiles

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#6786] opened 2023-01-18 04:18 UTC
### Description: 

On a new profile, you'll notice that the images/animations are missing from the `Brave News` opt-in modal/card via NTP.

### Steps to Reproduce 

  1. install/launch `1.46.2 (23.1.10.20)` and run through the initial onboarding
  2. once the NTP opens/is visible, notice that the images/animations are missing from the Brave News opt-in modal/card

### Actual result: 

![image](https://user-images.githubusercontent.com/2602313/213082075-1b5386ea-15b5-4935-8131-27207ef7b10f.png)

### Expected result:

![image](https://user-images.githubusercontent.com/2602313/213082142-77a15c0b-5ea9-4551-8471-ef63475dc91f.png)

### Reproduces how often: [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases outlined above.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Reproducible with `1.47 (23.1.17.15)`
- Can you reproduce this issue with the previous version of the current build from TestFlight? Reproducible with `1.46 (22.12.15.19)`
- Can you reproduce this issue with the current build from AppStore? Reproducible with `1.46.2 (23.1.10.20)`

### Device details: 

* `iPhone 11` running `iOS 16.2` - **Reproduced**

### Website problems only:
- did you check with Brave Shields down? `N/A` 
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A` 

### Additional Information

CCing @srirambv @Uni-verse @iccub

**Comment by kylehickinson** [comment] 2023-01-18 15:11
Duplicate of https://github.com/brave/brave-ios/issues/5636

**Closed as not planned by kylehickinson** 2023-01-18 15:11 UTC
Labels: closed/duplicate
