### ISSUE TITLE
No confirmation is shown when source list is reset

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3083] opened 2020-11-26 12:58 UTC
### Description: 
Reset feed doesn't show confirmation that its reset

### Steps to Reproduce 
  1. Enable all sources in Brave Today  apart from default ones
  2. Scorll to bottom and tap on reset 
  3. No confirmation is show. User has to go to individual list to check if its all reset to defaults

**Actual result:** 
No confirmation is shown when source list is reset

**Expected result:**
Show a popup alert that its reset 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.22(20.11.25.17)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment] 2020-11-26 15:56
Duplicate of https://github.com/brave/brave-ios/issues/2870

**Closed as completed by kylehickinson** 2020-11-26 15:56 UTC
Labels: closed/duplicate
