### ISSUE TITLE
"Look & Feel" section in "Shields" has ampersand entity name instead of the symbol.

### ISSUE THREAD

**Issue by chaithanya-hr** [brave/brave-ios#2594] opened 2020-06-01 11:39 UTC
### Description: 
The `Look & Feel` sub-heading under the `Shields` section has the ampersand entity name i.e `&amp;` instead of the ampersand symbol i.e `&`

### Steps to Reproduce 
  1. Launch Brave browser on iOS.
  2. Go to `brave://settings/`
  3. Scroll down to the `Shields` section
  4. The last sub-heading is `Look &amp; Feel`

**Actual result:**
<img width="1106" alt="Screenshot 2020-06-01 at 5 01 36 PM" src="https://user-images.githubusercontent.com/47441984/83405277-cdb49600-a429-11ea-80fe-6cd06669f073.png">

**Expected result:**
The sub-heading should be `Look & Feel` instead of `Look &amp; Feel`

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
Version 1.9.76(81.0.4044.138)

**Device details:** 
MacBook Pro (13-inch) macOS Catalina v10.15.3

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### Additional Information 
Nil

**Comment by srirambv** [comment] 2020-06-01 12:29
Closing as dupe of https://github.com/brave/brave-browser/issues/9690

**Closed as completed by srirambv** 2020-06-01 12:29 UTC
Labels: closed/duplicate, closed/invalid
