### ISSUE TITLE
Menu doesn't close after bookmark selection

### ISSUE THREAD

**Issue by mikel2000** [brave/brave-ios#4052] opened 2021-08-16 07:35 UTC
### Description: 
After selecting a bookmark from the bookmarklist, the menu screen doesn't close, so the selected website can't be seen. The menu screen must be closed manually.

Seems to be a regression in the used Brave version (see below), as it worked until yesterday before I updated to the new version.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
1.29 (21.8.3.10)

**Device details:** 
iPhone SE 2020, iOS 14.7.1

**Comment by iccub** [comment] 2021-08-16 11:38
This will be fixed in next build, should go live early this week,
closing as a duplicate of https://github.com/brave/brave-ios/issues/3950

**Closed as completed by iccub** 2021-08-16 11:38 UTC
Labels: closed/duplicate
