### ISSUE TITLE
Add option to enable YouTube playback at max quality 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#7472] opened 2023-05-16 21:22 UTC
### Description: 
YouTube typically serve video on lower quality (360p) when viewed on a web browser vs their app. 

Please add an option to enable playback at the max available quality.

In Settings > Appearance add the following under MODE

YOUTUBE PLAYBACK 
Enable Playback at Max Quality (On/Off) Default Off
Description: Enabling this experimental feature will playback video at the maximum quality available and will use additional data. 

(Exact location/placement TBD, lets discuss in Slack)

@rmcfadden3 can you check this setting text please ^

![IMG_1040](https://github.com/brave/brave-ios/assets/7606853/f0fdd8da-7ef9-4e3c-83e8-342543448f41)

**Comment by anthonypkeane** [comment] 2023-05-16 21:25
@Brandon-T maybe we can enable captions too in this setting, LMK. Thanks

**Comment by rmcfadden3** [comment] 2023-05-19 19:49
@anthonypkeane — your proposed copy LGTM.

Devil's advocate: do we need to specify that this is _YouTube's_ max quality (as opposed to some quality-level that Brave is imposing)? Or you think that's implied?

btw, what's the `Stats for nerds` thing? Is that our copy, or YouTube's?

**Comment by anthonypkeane** [comment] 2023-05-19 20:18
TY

Stats for nerds is a YT thing yes. Regarding the quality, we don't impose it, YT determine that.

**Comment by rmcfadden3** [comment] 2023-05-19 20:40
> TY
> 
> Stats for nerds is a YT thing yes. Regarding the quality, we don't impose it, YT determine that.

Right. That's what I meant: Should we specify that this is a YouTube max quality, so it doesn't imply Brave is imposing it? As in something like `Enable Playback at YouTube's Max Quality`

**Comment by iccub** [comment] 2023-05-24 10:44
duplicate of https://github.com/brave/brave-ios/issues/7055

**Closed as not planned by iccub** 2023-05-24 10:44 UTC
Labels: closed/duplicate

**Comment by anthonypkeane** [comment] 2023-06-01 16:36
https://github.com/brave/brave-ios/issues/7055
