### ISSUE TITLE
[Follow up to 7283] Title changes for first video from YT homepage when other videos added

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#7340] opened 2023-04-26 16:29 UTC
### Description: 
Follow up to https://github.com/brave/brave-ios/issues/7283

### Steps to Reproduce 

1. For example, open YT or Vimeo main page (where you see multiple videos on one screen)
2. Observe "Add to playlist" button in search bar > Tap it
3. Open Playlist now and confirm that video was added. Remember name and thumbnail pic
4. Go back to main page and scroll through the videos. Make sure "Add to Playlist" button is green
5. Open Playlist again > Observe, thumbnail and name for the first video is changed

### Actual result: 
If user added a file from the main page of YT (for example), then scrolled through the videos and opened Playlist, there will be shown wrong title and thumbnail for the first audio/video file in Playlist. Sometimes, whole video is replaced.

https://user-images.githubusercontent.com/17885425/234641488-e677b307-fb23-4234-817d-84a29eee7a99.MP4

### Expected result:
Correct thumbnail and name must be shown for each audio/video that were added to the Playlist

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

### Brave Version:  **1.50 (23.4.25.20)**

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
iPhone X, iOS 16.3.1

**Comment by Brandon-T** [comment] 2023-08-09 20:04
Cannot reproduce this issue anymore.

EDIT: Tested again. The playlist button no longer shows on the main youtube page. This was fixed in the "invisible" videos fix :)

**Closed as not planned** 2023-08-10 14:04 UTC
Labels: bug, QA/Yes, release-notes/include, Epic: Playlist
