### ISSUE TITLE
Send api_key with each usage ping GET request

### ISSUE THREAD

**Issue by aekeus** [brave/brave-ios#2182] opened 2020-01-11 21:20 UTC
## Problem Description 
Usage pings are currently accepted without verification. We would like to match an api_key with each usage request.

## Feature Overview
In the usage ping GET request please send an `api_key` header containing the value of the api key used for referral promo requests.

**Comment by kylehickinson** [comment] 2020-02-06 17:06
Duplicate of #2211

**Closed as completed by kylehickinson** 2020-02-06 17:06 UTC
Labels: closed/duplicate
