### ISSUE TITLE
UI sometimes freezes when Rewards are enabled

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3941] opened 2021-07-19 17:18 UTC
### Description: 
We've got few reports from users that sometimes when you visit a page with Rewards ON, the UI freezes for few seconds.
This happens on high end devices too.
I personally was unable to reproduce it.

Few websites that this happens on is Twitter, ESPN, CNN

### Steps to Reproduce 
  1. Rewards ON
  2. Start using the app, visiting pages.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by bsclifton** [comment] 2021-07-19 17:19
Internal notes (employee only) can be found here https://bravesoftware.slack.com/archives/C06UXF3KJ/p1625962370289400

**Comment by iccub** [comment] 2021-09-29 09:15
linked brave-core ticket here https://github.com/brave/brave-browser/issues/18118

**Comment by kjozwiak** [comment] 2021-09-29 17:50
Cases were also added via https://github.com/brave/brave-core/pull/10088#issue-996471207. @srirambv we'll need to double check with both @bsclifton & @jsecretan to see if they can still reproduce the issue once https://github.com/brave/brave-core/pull/10088 makes it into `1.32.x`.

**Comment by kjozwiak** [comment] 2021-09-29 18:06
Closing as https://github.com/brave/brave-core/pull/10280 was merged. We'll need to wait till @kylehickinson or @iccub can you let us know via this issue when we get a TF build that includes the above? Thanks.

**Closed as completed by kjozwiak** 2021-09-29 18:06 UTC
Labels: bug, QA/No, release-notes/include, Epic: Rewards, Epic: Ads

**Comment by iccub** [comment] 2021-09-29 18:36
I will let you know @kjozwiak and put brave-core library info in TF build description.

**Comment by srirambv** [comment] 2021-10-21 08:40
@iccub  confirmed that this is fixed and works fine now for both @jsecretan and @bsclifton . Since its pretty hard to repro and we have confirmation internally that its working fine, marking the issue as QA/No
