### ISSUE TITLE
AdblockEngine crashes upon initialization

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#8355] opened 2023-11-02 23:56 UTC
### Description: 
- Upon initialization of the AdblockEngine, it can crash the application
- https://github.com/brave/brave-ios

### Steps to Reproduce 
  1. Run the app, enable a lot of Filters in Brave Shields -> Privacy
  2. You can enable up to 40 at the moment.

### Actual result: 
- Crash

### Expected result:
- Should not crash at all

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Very difficult to reproduce on new devices! (Easy to reproduce on iPhone 6, 6s, SE or older devices)

### Brave Version: 
- 1.58.x, 1.58.1

### Device details: 
- iPhone

**Comment by iccub** [comment] 2023-11-03 14:21
duplicate of https://github.com/brave/brave-ios/issues/8334
I will copy yours ticket description to that ticket

**Closed as not planned by iccub** 2023-11-03 14:21 UTC
Labels: closed/duplicate
