### ISSUE TITLE
Lost Everything when Upgraded. 

### ISSUE THREAD

**Issue by norsehealer** [brave/brave-ios#1958] opened 2019-11-14 17:00 UTC
### Description: 
Upgraded last night (manual update) and opened today with no history, no saved passwords, no bookmarks, and no opened tabs. 

I’m not even sure it’s reproducible. 

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 
Empty history, no previously opened tabs. 

**Expected result:**
Update to not wipe out settings. 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
I can’t reproduce it. 

**Brave Version:** 
Version 1.13 (19.11.06.18)

**Device details:** 
iPhone 6 iOS 12.4.2 (16G114)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 
N/A

### Additional Information

**Comment by iccub** [comment] 2019-11-14 17:36
Do you remember what was your previous app version by any chance? Was it 1.12.1 or earlier?
The good news is that the database most likely isn't deleted, but failed at migration to new location, we might be able to provide some steps in order to retrieve it.

**Comment by norsehealer** [comment] 2019-11-14 17:55
I don’t know the old version. The past few upgrades I didn’t have a problem so I didn’t think of it happening. 

I haven’t tried to delete the app and reinstall. I did notice my sync locations or other devices was remembered.

**Comment by iccub** [comment] 2019-11-14 18:14
Thanks for your feedback, one more question:
Do you remember if the app crashed on the first launch after upgrade?

**Comment by norsehealer** [comment] 2019-11-14 18:27
I don’t remember that happening.

**Comment by iccub** [comment] 2019-11-14 23:16
Fyi it's very likely that the old database of bookmarks is still on your device, you can go to Files.app on your device, look for Brave container and see if there are files with .sqlite extension

One more q:
Do you know if your previous Brave app version supported Dark mode/themes?

**Comment by norsehealer** [comment] 2019-11-14 23:56
the brave app did not have dark mode.

i dont see any files with .sqlite. i dont really have file extensions at all.

just 3 Brave files. 3 Model files and 3 folders (downloads, safe-browsing-data, and tp-data).

**Comment by iccub** [comment] 2019-12-12 10:08
Fixed in https://github.com/brave/brave-ios/issues/2015

**Closed as completed by iccub** 2019-12-12 10:08 UTC
Labels: closed/duplicate

**Comment by iccub** [comment] 2020-01-06 18:19
Did 1.14.2 update help with your missing bookmarks @norsehealer?

Looking for user feedback since we had hard time reproducing it

**Comment by norsehealer** [comment] 2020-01-08 01:24
> Did 1.14.2 update helped with your missing bookmarks @norsehealer?
> 
> Looking for user feedback since we had hard time reproducing it

I swapped to Pixel 3a around the 16th and erased my iPhone.
