### ISSUE TITLE
Recent Search issue with empty query

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#3789] opened 2021-06-15 21:05 UTC
Possible that spaces or empty queries are creating recent records. Should trim and length check.
![Image from iOS](https://user-images.githubusercontent.com/318119/122123375-878f6200-cdf3-11eb-852a-8721f9315674.png)

**Comment by iccub** [comment] 2021-06-16 09:11
Duplicate of #3790

**Closed as completed by iccub** 2021-06-16 09:11 UTC
Labels: closed/duplicate
