### ISSUE TITLE
External app popup seems to be different 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3883] opened 2021-07-05 15:36 UTC
### Description: 
External app popup seems to be different 

### Steps to Reproduce 
  1. Install 1.28
  2. Visit https://shaun.net/resources/test-phone-numbers/
  3. Tap on any phone number, external app popup is not shown

**Actual result:** 
<img width=500 src=https://user-images.githubusercontent.com/17010094/124493090-24b73800-ddad-11eb-91c3-3cfb492b9844.png>

**Expected result:**
<img width=500 src=https://user-images.githubusercontent.com/17010094/124494536-defb6f00-ddae-11eb-840e-677996de3d92.png>

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.28(21.7.2.17)

**Device details:** 
iPad Pro

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? Yes has the same new UI 
<img width=500 src=https://user-images.githubusercontent.com/17010094/124494563-e753aa00-ddae-11eb-81bb-f2836ff64645.png>

### Additional Information
Safari on iPhone has a different behaviour for continuous popups which I think is a much better implementation that what we have
<img width=300 src=https://user-images.githubusercontent.com/17010094/124493462-91cacd80-ddad-11eb-9043-a5e8ce08fa1d.png>

cc: @anthonypkeane  to take a call on if we need to switch back to the old design or not for iPads and also consider using Safari's UI for iPhone's

**Comment by kylehickinson** [comment] 2021-07-05 15:51
I'm not sure this is a bug, since it's just an internal implementation detail of how `WKWebView` handles the detector types (Added here: https://github.com/brave/brave-ios/pull/3830). Even Safari on iPhone does not match Safari on Desktop in this scenario.

I believe Apple specifically shows the long-press menu on tap on iPad. You can find a matching menu if you long-press the phone number on iPhone. In Brave however we override the long-press menu so the resulting long-press ends up being different.

**Comment by kylehickinson** [comment] 2023-03-08 21:40
Going to close this as not a bug. We moved to only have data detectors enabled for phone numbers now as well so this will only appear for phone numbers

**Closed as not planned by kylehickinson** 2023-03-08 21:40 UTC
Labels: closed/not-actionable
