### ISSUE TITLE
URL bar icons are not shown until focus is set on another app

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#8477] opened 2023-11-24 12:26 UTC
### Description: 
URL bar icons are not shown until focus is set on another app

### Steps to Reproduce  (May not be accurate but its according to the recording)
  1. Launch browser after updating via TF
  2. Back/Forward/Tabs tray/Menu icons are not shown 
  3. Switch app or open a different app and relaunch browser
  4. All icons appear

### Actual result: 

Uploading Missing icons.MP4…

### Expected result:
Show icons all the time

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Intermittent 

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Device details: 
iPad Pro (iOS 16.7.2)

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @iccub @kylehickinson @hffvld @Uni-verse @kjozwiak

**Comment by kylehickinson** [comment] 2023-11-24 14:05
duplicate of https://github.com/brave/brave-ios/issues/8475

**Closed as not planned by kylehickinson** 2023-11-24 14:05 UTC
Labels: closed/duplicate
