### ISSUE TITLE
Can't open any links in a new tab

### ISSUE THREAD

**Issue by joha1** [brave/brave-ios#994] opened 2019-03-21 14:34 UTC
## Description 
A long press/touch on a link does not open the menu that lets me open that link in a new tab or to copy or share that link, when scripts are off.

## Steps to Reproduce

  -1. Switch off scripts in brave shields (they are set to off by default on a new install, it seems to me)
   1. Long press on Link 

## Actual result:

Nothing, or rather, the link gets opened in the current tab, after letting go.

## Expected result:

Popup menu that asks me what to do with that link.

## Reproduces how often: 
Easily reproduced.
Happens on all sites I have tested so far.

## Brave version (brave://version info)
`brave://version` doesn't work on iOS
Platform: iOS
Brave: 1.8 (19.02.28.23)

### Reproducible on current release:
NA on iOS

**Comment by iccub** [comment] 2019-03-21 17:28
Duplicate of https://github.com/brave/brave-ios/issues/830

As a quick workaround you can kill the app from app switcher and open again, and it should be working.
This is Apple's bug, although we will try to make some workaround to fix this

**Closed as completed by iccub** 2019-03-21 17:28 UTC
Labels: closed/duplicate

**Comment by joha1** [comment] 2019-03-22 07:26
The workaround suggested by @iccub does not appear to work for me. 
But good to hear that there's already work on this. The other issue didn't pop up in my search, sorry.

**Comment by cndouglas** [comment] 2019-04-03 00:01
I think this is a separate issue from #830. That issue has been fixed as of the current master (2da509e), but the context menu still does not open if scripts are blocked.

This issue might be because the handler that shows the context menu uses JavaScript (https://github.com/brave/brave-ios/blob/development/Client/Frontend/UserContent/UserScripts/AllFrames/AtDocumentEnd/ContextMenu.js).
