### ISSUE TITLE
Missing touchresponse on lower part of the screen, iPad in landscape

### ISSUE THREAD

**Issue by parsd51** [brave/brave-ios#5938] opened 2022-08-30 09:31 UTC
### Description: 
Missing touchresponse on lower part of the screen, iPad in landscape

### Steps to Reproduce 
  1. iPad in landscape
  2. Open e.g. https://www.openstreetmap.org/way/23239274
  3. Scroll down completely on the left side
  4. Press ‘Se historik’ (or likely History or See history)

**Actual result:** 
Nothing happens

**Expected result:**
History opens.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
1.42 (22.8.15.22)

**Device details:** 
iPad Air 4, iPadOS 15.6.1

**Website problems only:**
- did you check with Brave Shields down? Same issue
- did you check in Safari/Firefox (WkWebView-based browsers)? No problem in Safari

### Additional Information
Above is just an example, it happens on the whole lower part of the screen.
Pressing a little above ‘Se historik’ opens the history as expected.
Problem doesn’t occur in portrait.
I suspect it happened when ajusting the size of the “URL input section”

**Comment by kylehickinson** [comment] 2022-08-30 13:25
Hey @parsd51 this is fixed already and will go out in the next release, sorry!

**Comment by kylehickinson** [comment] 2022-08-30 13:25
Duplicate of https://github.com/brave/brave-ios/issues/5846

**Closed as not planned** 2022-08-30 13:26 UTC
Labels: closed/duplicate
