### ISSUE TITLE
Add support for Playlist Folders

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3679] opened 2021-05-11 23:30 UTC
### Description: 
Add support for Playlist Folders
The user should be able to password protect a folder using the the iOS authentication method
 - see https://github.com/brave/brave-ios/issues/3649 for some context 

@jamesmudgett for a design

**Comment by iccub** [comment] 2021-11-26 16:04
duplicate of https://github.com/brave/brave-ios/issues/4352

**Closed as completed by iccub** 2021-11-26 16:04 UTC
Labels: closed/duplicate
