### ISSUE TITLE
Can't see the last bookmark 

### ISSUE THREAD

**Issue by crazyyzarc** [brave/brave-ios#3842] opened 2021-06-24 05:46 UTC
Currently it is difficult to click the last bookmark in the bookmark history, because it automatically disappears behind the bar with the pen and the folder.

My version: `1.27`
My operation system: `iOS 14.6`
My smartphone: `iPhone 8 Plus`

![Screenshot 2021-06-24 at 07 34 59](https://user-images.githubusercontent.com/4954535/123208918-2d139700-d4c0-11eb-9653-4b1b9c7adbe1.png) 
![Screenshot 2021-06-24 at 07 35 04](https://user-images.githubusercontent.com/4954535/123208950-3997ef80-d4c0-11eb-8d06-fb5f96de6939.png)

**Comment by iccub** [comment] 2021-06-24 07:47
Thanks for report, we want to fix it in next release.
Closing as a duplicate of https://github.com/brave/brave-ios/issues/3788

**Closed as completed** 2021-06-24 09:50 UTC
Labels: closed/duplicate
