### ISSUE TITLE
Sharing menu shares incorrect page all the time

### ISSUE THREAD

**Issue by balintbarna** [brave/brave-ios#3746] opened 2021-05-30 11:37 UTC
### Description: 
The link in the sharing menu is incorrect

### Steps to Reproduce 
  1. open a tab
  2. navigate around to different pages
  3. try to share the current page in a messaging app for example

**Actual result:** 
![image](https://user-images.githubusercontent.com/13272850/120102461-6ff57f80-c14b-11eb-9ae1-8b460363c83f.png)
As the screenshot demonstrates, the shared page is different from the current page

**Expected result:**
The shared page should be the current page

**Reproduces how often:**
Very often and very annoying

**Brave Version:** 
1.25.1 (21.5.21.22) but it's been like this for a few weeks now

**Device details:** 
iPhone SE 2020
currently iOS 14.5.1 but the bug is not new in this version

**Comment by kylehickinson** [comment] 2021-05-30 14:06
Hi @balintmaci, thanks for your report. This has been fixed and will be available in the next release

**Comment by kylehickinson** [comment] 2021-05-30 14:06
Duplicate of https://github.com/brave/brave-ios/issues/3246

**Closed as completed** 2021-05-30 14:07 UTC
Labels: closed/duplicate

**Comment by balintbarna** [comment] 2021-07-06 16:53
@kylehickinson the issue is present again, although not every time
![image](https://user-images.githubusercontent.com/13272850/124638549-5d2d4380-de8b-11eb-8443-82a050270a51.png)
Version 1.27.1 (21.6.22.16)
Device iPhone12,8 (iOS 14.6)
