### ISSUE TITLE
Favicons are not synced

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-ios#2998] opened 2020-10-29 15:01 UTC
### Steps to Reproduce 
DeviceA: Ubuntu 18.04 LTS
DeviceB : iPhone SE

1. Clean install on DeviceA and DeviceB
1. Establish sync chain between DeviceA and DeviceB
1. DeviceA: Open interia.pl and bookmark it
1. Wait till the bookmark is synced to DeviceB
1. Check favicon on DeviceB

Note: Issue also reproduces when devices are switched

**Actual result:** 
Favicon is not synced
![IMG_0049](https://user-images.githubusercontent.com/34715963/97591439-eb4d5200-19ff-11eb-907a-486e0c191d27.PNG)

**Expected result:**
Favicon is synced
![IMG_0050](https://user-images.githubusercontent.com/34715963/97591540-028c3f80-1a00-11eb-9d40-7acce343a631.PNG)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.21 (20.10.27.20), iPhone SE (iOS 12.4)

Brave | 1.18.5 Chromium: 86.0.4240.111 (Official Build) nightly (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @jsecretan @iccub @Brandon-T

**Comment by kylehickinson** [comment] 2020-10-29 16:09
I believe this is by design, but I'll let Brandon comment on it.

**Comment by Brandon-T** [comment] 2020-10-30 13:39
Hi. This was done on purpose. I did add FavIcon support to the sync side, but icons from Desktop look extremely bad.. Their icons are exactly 16 x 16px and doesn't take into account scaling or DPI.. Desktop purposely scales icons to this resolution. As a result it looks like:

![image](https://user-images.githubusercontent.com/1530031/97711668-c0acd900-1a93-11eb-9556-610df164d892.png)


so I figured we should just use the ones from iOS side + default monogram icons until the user visits the page.
If we still want to use the above favIcons from Desktop, let me know.

**Comment by diracdeltas** [comment] 2020-10-31 00:33
For privacy reasons, we should avoid fetching all the favicons at once when the user syncs for the first time if we decide to fetch them.

**Comment by iccub** [comment] 2020-11-02 17:44
Should be fixed in `Brave Dev 1.21 (20.11.2.17)` please retest

**Closed as completed by iccub** 2020-11-02 17:44 UTC
Labels: bug, QA Pass - iPhone X, QA/Yes, release-notes/exclude, QA Pass - iPhone, QA Pass - iPad, Epic: Sync

**Comment by srirambv** [comment] 2020-11-04 18:46
Verification passed on iPhone 7+ with iOS 14.1 running 1.21(20.11.2.20)
- Verified favicons are sync'd from desktop 
-------------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.11.2.20)
- Verified favicons are sync'd from desktop 
-------------
Verification passed on iPad Pro with iOS 14.1 running 1.21(20.11.2.20)
- Verified favicons are sync'd from desktop 
-------------
Verification passed on 1.21(20.11.2.20) on iPhone SE (iOS 12.4)
- Verified favicons are sync'd from desktop 

- Logged follow up issue for low resolution icons #3008
