### ISSUE TITLE
Device removed from sync chain still receives new bookmarks/folders

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#952] opened 2019-03-08 16:21 UTC
### Description: 
Device removed from sync chain still receives new bookmarks/folders

### Devices
Device 1: Ubuntu 18 running 0.61.47
Device 2: iPhone 7+ running 1.9(19.3.6.15)

### Steps to Reproduce 
  1. Add bookmarks and create sync chain on desktop
  2. Add iPhone to sync chain using QR code, ensure bookmarks sync
  3. Remove desktop from iPhone under devices, ensure desktop shows sync home page 
  4. Add new bookmarks/folders on iPhone, after a while, new bookmarks/folders are sync'd on desktop as well

**Actual result:** 
Desktop getting bookmarks after removed from sync chain
![image](https://user-images.githubusercontent.com/17010094/54040427-53985180-4193-11e9-8926-eb86f37a8fa7.png)
iOS sync chain with only one device 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17010094/54040791-3021d680-4194-11e9-8729-82d2522f5542.gif)

**Expected result:**
Once device is removed any new bookmarks added should not be propagated to any device that was removed from the sync chain

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment] 2019-03-08 17:20
Any bookmark added on desktop gets sync'd to iOS device as well.

**Comment by iccub** [comment] 2019-03-12 17:43
Could you check if this happens on Android?

From my tests I noticed that the device doesn't get correctly deleted on desktop.
Look at SS below,

I synced 3 devices: iPhone, iPad, desktop
On iPad removed desktop, and as on the screenshot, it still shows sync menu with only iPhone and iPad

This still might indicate that our `delete device` command is wrong and doesn't work well with desktop

<img width="1552" alt="Zrzut ekranu 2019-03-12 o 18 29 40" src="https://user-images.githubusercontent.com/6950387/54222755-56c67100-44f6-11e9-9359-8ada7934f4fd.png">

**Comment by iccub** [comment] 2019-03-12 17:56
Found this issue on desktop https://github.com/brave/brave-browser/issues/3509

I think it needs a fix on desktop, not on iOS

**Comment by jhreis** [comment] 2019-03-20 17:21
This is certainly a desktop issue. It got the removal request from iOS since it updated the UI, but continues retrieving and sending bookmarks. Closing per @iccub's investigation.

**Closed as completed by jhreis** 2019-03-20 17:21 UTC
Labels: bug, QA/Yes, release-notes/exclude, release/blocking

**Comment by GeetaSarvadnya** [comment] 2019-03-26 12:33
The issue is reproducible on 1.9 (19.03.25.21)- iPhone8

@srirambv As per above comments issue is with Desktop, are you going to add an issue in bc desktop?

**Comment by iccub** [comment] 2019-03-26 12:45
@GeetaSarvadnya it's logged here https://github.com/brave/brave-browser/issues/3509

**Comment by srirambv** [comment] 2019-03-27 16:00
This issue needs to be reverified once brave/brave-browser#3509 is fixed. 

cc: @brave/legacy_qa

**Comment by kjozwiak** [comment] 2019-03-28 04:40
Reproduced the original issue using the following builds: 
* `1.9 (19.3.27.19)` on `iPad Mini 4`
* `0.61.52 Chromium: 73.0.3683.86`

I couldn't reproduce the issue using the following builds:
* `1.9 (19.3.27.19)` on `iPad Mini 4`
* `0.64.22 Chromium: 73.0.3683.75`

Went through the original STR three times using `0.64.22 Chromium: 73.0.3683.75` and waited ~30min. Once desktop was removed from the sync chain, it never received new changes as expected.

**Comment by kjozwiak** [comment] 2019-03-28 04:41
* Verification **PASSED** with `1.9 (19.3.27.19)` on `iPad Mini 4` using the original STR mentioned under https://github.com/brave/brave-ios/issues/952#issue-418856501. Also left comment under https://github.com/brave/brave-ios/issues/952#issuecomment-477445283.
