### ISSUE TITLE
Open Youtube video urls within app

### ISSUE THREAD

**Issue by chkk525** [brave/brave-ios#2892] opened 2020-09-24 03:24 UTC
## Problem Description 

- Currently, when a user clicks Youtube video links on the google search result page, the Youtube app opens if he has already installed it.
- Some users might prefer opening within Brave browser instead Youtube app.

## Feature Overview 

- Open google search result (videos tab): [example](https://www.google.com/search?q=brave&prmd=nvi&sxsrf=ALeKk01yx-9b4RIWp-_yyfouIO2SERHLWw:1600917695744&source=lnms&tbm=vid&sa=X&ved=2ahUKEwj0zMaU64DsAhULL6YKHa_JClkQ_AUoAnoECBYQAg&biw=375&bih=646&dpr=3#ip=1)
- Click Youtube video
- Open the video in Brave browser

## Design 

- No design needed

## Implementation Details 

##User Experience 

   1. 
   2. 
   3. 

### Additional information

- Firefox Focus already has this feature

**Comment by kylehickinson** [comment] 2020-09-24 14:35
Duplicate of #2119

This is not officially under our control, and is just how WKWebView works. The only way to support it is to use a private undocumented API as discussed in the original ticket. Perhaps the discussion could be re-opened in favour or using it again.

**Closed as completed** 2020-09-24 14:36 UTC
Labels: closed/duplicate

**Comment by Xanthorrhoea** [comment] 2020-09-25 00:59
I personally just uninstall the youtube app because i prefer the in browser experience even on mobile.
