### ISSUE TITLE
Chromium `BrowserMetrics` folder creates persisted files every launch

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6925] opened 2023-02-10 20:58 UTC
### Description: 

A Chromium bump caused a change in behaviour around the metrics service that deals with persistent histograms.

This creates a `BrowserMetrics-{id}.pma` file over and over again but never cleans it up.

### Steps to Reproduce 
  1. Launch the app and close it multiple times
  2. Verify in the app sandbox that the `Application Support/Chromium/BrowserMetrics` folder grows endlessly

### Expected result:
The `Application Support/Chromium/BrowserMetrics` folder should persist

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

### Brave Version:
Cr109+ but haven't tested farther back

**Comment by iccub** [comment] 2023-02-15 18:19
Duplicate of https://github.com/brave/brave-ios/issues/6948

**Closed as not planned by iccub** 2023-02-15 18:19 UTC
Labels: closed/duplicate
