### ISSUE TITLE
App switches to Amazon app without permission

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#914] opened 2019-02-20 15:34 UTC
### Description: 
App switches to Amazon app without permission

### Steps to Reproduce 
  1. Search for something on Google
  2. Click on a result with Amazon link
  3. Immediately switches to Amazon app without asking permission first

**Actual result:** 
App switches to Amazon app without permission

**Expected result:**
Should ask permission before switching to other apps

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.8 and Appstore build

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
Issue doesn't reproduce with embedded twitter links, opens in a new tab

**Comment by kylehickinson** [comment] 2019-02-20 15:45
Duplicate of #551 

(Open PR still needing work: #619)

**Closed as completed by kylehickinson** 2019-02-20 15:45 UTC
Labels: bug, closed/duplicate, QA/Yes, release-notes/exclude
