### ISSUE TITLE
WebAuthn modal displayed on pintrest

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#2176] opened 2020-01-09 21:32 UTC
### Description: 

On navigating to `pintrest` and `pinimg.com` the U2F modal to insert keys is being displayed.

![Screen Shot 2019-12-07 at 1 22 35 PM](https://user-images.githubusercontent.com/1903815/72106557-72e89980-32e4-11ea-943e-088f1274b3a2.png)

**Actual result:** 
Displayed

**Expected result:**
Should not be displayed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment] 2022-02-09 04:35
Closing as we've deprecated the `Yubikey` SDK in favour of the `WKWebView` SDK as per https://github.com/brave/brave-ios/issues/4473. QA went through verifications via https://github.com/brave/brave-ios/issues/4473#issuecomment-1032291511, https://github.com/brave/brave-ios/issues/4473#issuecomment-1033102239 & https://github.com/brave/brave-ios/issues/4473#issuecomment-1033240109 and couldn't reproduce the crashes using the `WKWebView` SDK.

**Closed as completed by kjozwiak** 2022-02-09 04:35 UTC
Labels: QA/No, release-notes/exclude, Epic: WebAuthn
