### ISSUE TITLE
Clicking on token ID doesn't load the actual Token URL

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#6551] opened 2022-12-05 19:42 UTC
### Description: 
Clicking on token ID doesn't load the actual Token URL

### Steps to Reproduce 
  1. Add an NFT to visible token list
  2. Click on the NFT to load NFT view
  3. Click on the token ID
  4. Page loads but just loads the main domain and not the actual token details page

**Actual result:** 

BSC | Ethreum
-- | --
![image](https://user-images.githubusercontent.com/17010094/205727834-9f1f7b8f-c873-4bed-90c3-d19e1e16cc09.png) | ![image](https://user-images.githubusercontent.com/17010094/205727862-85d2d0aa-de23-47d3-9078-449cb9546d48.png)

**Expected result:**
Load actual URL 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.46 (22.12.3.0)

**Device details:** 
iPhone 7+ (iOS 14.8.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information 
cc: @nuo-xu @StephenHeaps @diracdeltas

**Comment by StephenHeaps** [comment] 2022-12-05 22:39
I believe this is caused by https://github.com/brave/brave-ios/issues/6521. Should be available in next build.

**Comment by soner-yuksel** [comment] 2022-12-06 19:11
It should be fixed with https://github.com/brave/brave-ios/pull/6575

**Closed as not planned** 2022-12-09 17:17 UTC
Labels: closed/duplicate
