### ISSUE TITLE
Edited bookmark name never gets synced in brave core

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#990] opened 2019-03-19 02:10 UTC
### Description: 
Found while testing #682 
Edited bookmark name never gets synced in brave core

### Steps to Reproduce 
  1. Create a sync chain between iPhone and Bravecore 
  2. Create a bookmark folder A in iPhone
  3. Bookmark few sites into a folder A
  4. Verify that, folder A along with bookmarks synced in BC 
  5. Tap on bookmarks Edit and edit any site name ( e.g: I have edited `Amazon.com: Online shopping for electronics...` to only `Amazon.com`)
  6. The edited name `Amazon.com` never gets synced in brave core

**Actual result:** 
Edited bookmark name never gets synced in brave core

**Expected result:**
Edited bookmark name should get synced in brave core

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
Brave IOS: 1.9 
Brave Core: 0.61.51

**Device details:** 
iPhone 8

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by iccub** [comment] 2019-03-19 10:55
Duplicate of https://github.com/brave/brave-ios/issues/951
This will get fixed in the next beta build

**Closed as completed by iccub** 2019-03-19 10:55 UTC
Labels: bug, closed/duplicate, QA/Yes
