### ISSUE TITLE
[Feature] Custom Search Engines

### ISSUE THREAD

**Issue by David-Beetle** [brave/brave-ios#1509] opened 2019-09-08 06:36 UTC
## Basic Information
**Feature/Issue Overview**: 
I am a  big fan of not yet listed search engines like [Jive Search](https://jivesearch.com). I also appreciate searching websites like [Invidious](https://invidio.us/) and Lemmy.

However, Brave-IOS does not currently support or allow for users to add custom search engines.

## Design 
This is how FireFox does it:

![firefox-ios-add-search-engine](https://coinsh.red/ipfs/QmctW8j25tkjnyyhXb1G65MqYuCVM1odQLSDL4Zj1uovUZ)

I figured the same model would be used.

### Additional information

Hope you don't mind me removing portions of the PR template. Most of the requested information was not applicable to this issue.

_____________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/80050334-feature-custom-search-engines)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/BountySource).

**Comment by iccub** [comment] 2019-09-09 08:49
https://github.com/brave/brave-ios/pull/983

There is a work for it already, we should be able to ship it for 1.13 release :)
1.12 shipping soon to support iOS 13, 1.13 will be like a month from now or something

I will close this ticket as duplicate of https://github.com/brave/brave-ios/issues/936, feel free to comment in the open ticket

**Closed as completed by iccub** 2019-09-09 08:49 UTC
Labels: closed/duplicate

**Comment by isaacjara17** [comment] 2020-11-04 12:00
> There is a work for it already, we should be able to ship it for 1.13 release :)
> 1.12 shipping soon to support iOS 13, 1.13 will be like a month from now or something

Well, that was over a year ago. Any updates? It was my favorite feature
