### ISSUE TITLE
No SNTP image is shown when toggle the `Show sponsored images` switch 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#2269] opened 2020-01-29 10:48 UTC
### Description: 
No SNTP image is shown when toggle the `Show sponsored images` switch 

### Steps to Reproduce 
  1. Clean profile 1.14.3
  2. Enable rewards through on-boarding
  3. Open SNTP saw sponsored image once 
  4. Navigate to settings->New Tab page->Turn off `Show sponsored images`
  5. Remove the app from memory
  6. Relaunch the app and navigate to settings->New Tab page->Turn on `show sponsored images`
Actual: No sponsored images are shown.

**Actual result:** 
No SNTP image is shown when toggle the `Show sponsored images` switch to ON

**Expected result:**
SNTP images should be shown when `Show sponsored images`switch is ON

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 

1.14.3 (20.01.28.18)
**Device details:** 
iPhone 8 - IOS 13.3

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @brave/legacy_qa @jhreis @davidtemkin @anthonypkeane @jamesmudgett

**Comment by iccub** [comment] 2020-01-29 11:08
Duplicate of https://github.com/brave/brave-ios/issues/2268

**Closed as completed by iccub** 2020-01-29 11:08 UTC
Labels: closed/duplicate
