### ISSUE TITLE
Upload Photo to Twitter Issue

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#4198] opened 2021-09-20 19:00 UTC
### Description: 
Per: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1632007777191400

Attempting to upload photo to Twitter consistently gives me the following message. Shields seem to have no effect, and the same images work in Safari. Using v1.30.1.

![Image from iOS](https://user-images.githubusercontent.com/7606853/134058993-d4408b6e-b61f-4e5b-a222-f2c335154f6a.png)

cc @Jacalz 

Similar to https://github.com/brave/brave-browser/issues/10195

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
1.31

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment] 2023-03-02 16:32
I tried and can't reproduce. Closing for retesting

**Closed as completed by iccub** 2023-03-02 16:32 UTC
Labels: bug, QA/Yes, release-notes/exclude, QA Pass - iPhone

**Comment by Uni-verse** [comment] 2023-03-31 19:45
Tested on `iPhone 12` running `iOS 16.4` using version `1.49 (23.3.31.9)`

- Ensured adding multiple images from storage in the compose message form works on twitter.com
- Ensured adding hi res images does not show the warning message in https://github.com/brave/brave-ios/issues/4198#issue-1001294208

Example | Example | Example
-|-|-
![IMG_4670](https://user-images.githubusercontent.com/17885425/229214945-b6442c4b-3110-4a94-af77-eef71c012b90.PNG) | ![IMG_4671](https://user-images.githubusercontent.com/17885425/229214958-e785841c-dc3d-4b1f-ace5-14a3dd6f14e1.PNG) | ![IMG_4672](https://user-images.githubusercontent.com/17885425/229214968-6a556783-1101-4c15-a833-3078b2551aca.PNG)
