### ISSUE TITLE
'Claim my rewards' button on modal doesn't work the first time

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#2280] opened 2020-01-29 22:11 UTC
### Description: 
Found while testing https://github.com/brave/brave-ios/issues/2255

The first time you get the `Claim my rewards` modal on a NTP and you tap the button, your rewards aren't claimed. You have to either a) claim from the panel or b) trigger this modal again. On triggering it again the second claim will be successful.

### Steps to Reproduce 
  1. install `1.14.3 (20.1.29.20)` via the `Dev` TF channel
  2. skip the `Onboarding` process and go into `Settings` --> `View Rewards Debug Menu`
  3. select `Staging` and restart the browser (should close automatically)
  4. once the browser is relaunched, enable rewards via the panel (`Join Rewards`)
  5. go into `Settings` --> `View Rewards Debug Menu`
  6. restore a wallet that has an ad grant available (use the shared GDoc) and restart the browser
  7. open the panel and then a NTP and you'll get the `Brave Reward` modal that displays your ad grant
  8. Tap on `Claim my rewards` button.

**Actual result:** 
Modal closes, rewards are not claimed. 
You must either:
a. Tap on the panel and claim from there 
OR
b. Close the app, remove from memory. Relaunch, open the panel, and then open a NTP. This will trigger the modal again and claiming from this second modal will work.

**Expected result:**
Claim should work from modal the first time.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.14.3 (20.1.29.20)

**Device details:** 
iPad 5th Gen iOS12 and iPad mini iOS13

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc @brave/legacy_qa @jhreis @iccub

**Comment by kjozwiak** [comment] 2020-01-30 08:34
@kylehickinson pointed out that this might be related/the same issue as https://github.com/brave/brave-ios/issues/1998.

**Comment by iccub** [comment] 2020-01-30 08:37
Also wanted to note that with current implementation, the 'Claim Rewards' notification on NTP is attempted on every app launch.
So if it fails on first claim, the user still gets the prompt next time, until there's grant no available

**Comment by iccub** [comment] 2020-01-30 18:28
Bumping to next release as we are still not sure what is source of the problem

**Comment by kylehickinson** [comment] 2020-01-30 18:41
Duplicate of #1998

**Comment by iccub** [comment] 2020-02-07 15:24
Just tested on prod and it works correctly, closing for now. Reopen if this happens on prod to you

**Closed as completed by iccub** 2020-02-07 15:24 UTC
Labels: bug, QA Pass - iPhone X, QA/Yes, release-notes/include, QA Pass - iPhone, QA Pass - iPad, test-plan/specified, Epic: Rewards, Epic: NTP

**Comment by srirambv** [comment] 2020-02-20 10:01
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.18.17)
- Verified able to claim UGP grant in the first try
----
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified able to claim UGP grant in the first try
----
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.18.17)
- Verified able to claim UGP grant in the first try
----
Verification passed on iPad Pro with iOS 12.4.5 running 1.15(20.02.18.17)
- Verified able to claim UGP grant in the first try
----
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified able to claim UGP grant in the first try
----
