### ISSUE TITLE
Background Video Play Experience

### ISSUE THREAD

**Issue by EyanGoldman** [brave/brave-ios#1390] opened 2019-08-13 19:32 UTC
User experience for playing video in background.
Please refer to: https://docs.google.com/document/d/1j_DlNjFOwa-mfIsZXat6YH7uAMHH46fySul2yYsAT1I/edit?usp=sharing

cc: @karenkliu for mocks

**Comment by iccub** [comment] 2019-12-10 12:36
Duplicate of https://github.com/brave/brave-ios/issues/902

**Closed as completed by iccub** 2019-12-10 12:36 UTC
Labels: closed/duplicate
