### ISSUE TITLE
Excessive space usage by Brave 

### ISSUE THREAD

**Issue by specter78** [brave/brave-ios#2947] opened 2020-10-08 18:45 UTC
The browser is storing >600 MB data apart from app size. And this space is used even after clearing all downloads and web data.

(I removed other headings as they seemed irrelevant)

**Comment by bsclifton** [comment] 2020-10-23 05:58
@kylehickinson does 1.20 have the publisher v4 changes? I think it has `brave-core` v1.10 (and fix was in 1.12)

Our next release 1.21 should fix this 😄 @specter78 do you have rewards on?

**Comment by specter78** [comment] 2020-10-23 10:44
Rewards are disabled.

**Comment by specter78** [comment] 2020-11-12 03:22
Updating to 1.21 does **not** resolve the issue.

**Comment by bsclifton** [comment] 2020-12-01 22:57
Thanks for the report @specter78 - we did identify the issue and are working on a fix

**Comment by bsclifton** [comment] 2020-12-01 22:58
Closing as a duplicate of https://github.com/brave/brave-ios/issues/3099 - please subscribe there for updates

**Closed as completed by bsclifton** 2020-12-01 22:58 UTC
Labels: closed/duplicate, Epic: Rewards
