### ISSUE TITLE
iOS15 UI menu bug on iPad

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#4240] opened 2021-09-27 23:34 UTC
### Description: 
I'm seeing a a UI bug on the iPad menu, image attached. 

![Open a New Browser Tab](https://user-images.githubusercontent.com/7606853/134999004-2378b79c-b121-4e01-9914-3255e1930d5e.png)

**Comment by iccub** [comment] 2021-09-28 10:02
This is fixed in 1.31,
duplicate of https://github.com/brave/brave-ios/issues/4188

**Closed as completed by iccub** 2021-09-28 10:02 UTC
Labels: closed/duplicate
