### ISSUE TITLE
App background uses wrong color on Dark Mode / Bookmarks from shortcut presents as a sheet

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#1552] opened 2019-09-17 21:14 UTC
# Description: 

### Steps to Reproduce 
  1. Turn on dark mode if not already on
  2. Enable bookmarks shortcut from settings
  3.  Click bookmarks shortcut

**Actual result:** 

![Image from iOS](https://user-images.githubusercontent.com/529104/65080011-56f46d00-d96e-11e9-9890-6ba40c798826.jpg)

**Expected result:** Background should be black _or_ bookmarks should be presented full-screen like from the menu instead of as a sheet
**Reproduces how often:** Easily, until private mode is accessed at least once
**Brave Version:** 1.12 Live
**Device details:** iPhone X 13.0 GM

**Comment by srirambv** [comment] 2019-10-17 17:07
This is still an issue on iPhone 6 running iOS 12.4 the bottom bar of the bookmarks page is in white as compared to other pages history/downloads
[#1552.zip](https://github.com/brave/brave-ios/files/3740442/1552.zip)

@iccub is this expected behaviour for iOS 12? Seems to be fixed on iOS 13

**Comment by iccub** [comment] 2019-10-17 17:23
reopen @srirambv, i'll fix it

**Closed as completed** 2019-10-18 14:20 UTC
Labels: bug, QA Pass - iPhone X, QA/Yes, release-notes/exclude, QA Pass - iPhone, QA Pass - iPad, Epic: UI/UX

**Comment by srirambv** [comment] 2019-10-18 20:24
Verification passed on iPhone Xr with iOS 13.2 running 1.13(19.10.18.15)
* Verified changing theme to dark and opening downloads shows fullscreen and uses the correct colour 

Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.10.18.15)
* Verified changing theme to dark and opening downloads shows fullscreen and uses the correct colour 

Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.18.15)
* Verified changing theme to dark and opening downloads shows fullscreen and uses the correct colour 

Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.18.15)
* Verified setting theme to dark in settings and opening downloads opens up in full screen and uses the correct colour 

Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.18.15)
* Verified setting theme to dark in settings and opening downloads opens up in full screen and uses the correct colour
