### ISSUE TITLE
brave flashes black when restoring from background and YT desktop is the active tab

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2248] opened 2020-01-28 05:42 UTC
### Description: 

When you have `YouTube` (desktop version of the website) as the active tab and load Brave from the background, you'll notice a "black" flash before YT becomes visible.

* https://www.youtube.com --> `Reproducible`
* https://m.youtube.com --> `Not reproducible`

### Steps to Reproduce

  1. install & launch `1.14.2 (19.12.12.17)`
  2. load https://www.youtube.com in a tab (ensure it's the desktop version of the website)
  3. once YT has loaded, background Brave
  4. load Brave from the background and you'll notice a the webview will flash "black"

**Actual result:** 

Example of the issue occurring: https://youtu.be/sQ5lPEV1OkQ

**Expected result:**

Brave shouldn't be flashing back when

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible when using the STR mentioned above.

**Brave Version:** 

* `1.14.2 (19.12.12.17)` - **Reproduced**
* `1.14.3 (20.01.27.18)` - **Reproduced**

**Device details:** 

* `iPad Mini 4` using `iOS 12.4.1` - **Reproduced**
* `iPhone 6s+` using `iOS 12.4.1` - **Couldn't reproduce**
* `iPad Air 3rd Gen` using `iOS 13.3` - **Couldn't reproduce**
* `iPhone 11` using `iOS 13.3` - **Couldn't reproduce**

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @srirambv @anthonypkeane

**Comment by Brandon-T** [comment] 2020-02-12 16:16
Hmm.. I am unable to reproduce this on my iPhone and any devices on Simulator. Does this happen ONLY for Youtube? Or does it also happen for Vimeo and DailyMotion or other video sites?

**Comment by kjozwiak** [comment] 2020-02-17 10:18
@Brandon-T looks like it's happening on both `vimeo.com` and `dailymotion.com` as well using `1.4.3 (20.02.01.06)`. Seems like it's less reproducible on those websites though. On YT, it's basically 100% reproducible. On both `Daily Motion` and `Vimeo`, it happens a few times and it eventually stops till you scroll to a new area and try reproducing it again. Assuming it has something to do with loading video previews? But YT doesn't seem to do any "previews" but is 100% reproducible. Let me know if there's anything that I can do to help 👍

**Comment by iccub** [comment] 2021-05-06 16:11
Since this is iOS 12 only im gonna close it, we do not support ios12 anymore

**Closed as completed by iccub** 2021-05-06 16:11 UTC
Labels: bug, QA/Yes, iPad-specific, test-plan/specified, closed/wontfix
