### ISSUE TITLE
Browser crashes when opening rust-lang forums website

### ISSUE THREAD

**Issue by gridlocdev** [brave/brave-ios#7970] opened 2023-08-27 00:31 UTC
### Description: 

The browser crashes after loading any webpage on the rust-lang user forum https://users.rust-lang.org/

### Steps to Reproduce 
  1. Open Brave Browser
  2. In the search bar, navigate to https://users.rust-lang.org/t/ocaml-vs-rust-for-writing-compilers/76051

### Actual result: 

The browser crashes and returns back to the iOS home screen

### Expected result:

The webpage for the rust-lang forum appears and does not crash the browser

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Always

### Brave Version: 

Version 1.56 (23.8.4.21)

- Can you reproduce this issue with the most recent build from TestFlight?   N/A
- Can you reproduce this issue with the previous version of the current build from TestFlight?   N/A
- Can you reproduce this issue with the current build from AppStore?   Yes

### Device details: 

iPhone XR, iOS 16.6 
iPad Air 4, iPadOS 16.6

### Website problems only:
- did you check with Brave Shields down?   Yes
- did you check in Safari/Firefox (WkWebView-based browsers)?   Yes: Safari, Firefox, and DuckDuckGo Browser do not encounter this issue

### Additional Information

- I remember being able to reproduce this issue several months ago as well.
- Interestingly enough, this crash does not happen on other Discourse-based forums like Fedora (https://discussion.fedoraproject.org/) and Joplin (https://discourse.joplinapp.org)

**Comment by iccub** [comment] 2023-08-28 13:38
Fixed in 1.57 sorry for that.
We hope the build will go live this week

**Comment by iccub** [comment] 2023-08-28 13:54
duplicate of https://github.com/brave/brave-ios/issues/7026

**Closed as not planned by iccub** 2023-08-28 13:54 UTC
Labels: closed/duplicate
