### ISSUE TITLE
Can't switch between private tabs and normal tabs, without closing all private tabs first

### ISSUE THREAD

**Issue by dave90dave** [brave/brave-ios#3441] opened 2021-03-19 09:59 UTC
### Description: 
When I open private tabs, I am not able to switch between private tabs and normal tabs, without closing al my normal tabs first.

### Steps to Reproduce 
  1. Open a normal tab in brave iOS
  2. Open 2 private tabs in brave iOS
  3. Click on private, to switch from private tabs back to normal tabs.
  4. Now, all your private tabs are closed.

**Actual result:** 
All the private tabs close, once you switch back to your normal tabs.

**Expected result:**
That the private tabs stay open, so that you can switch between private and normal tabs without needing to close all private tabs first

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
always

**Brave Version:** 
1.23.1 (21.2.24.16)

**Device details:** 
Iphone SE 2020

### Additional Information
It might be great, if the private tabs will not be closed, so that you can switch between normal and private tabs without closing them first.

**Comment by iccub** [comment] 2021-03-19 12:56
We did this for security reasons, but we're hearing more and more voices that users want to keep their private tabs. We are going to look into it soon

I will close this ticket as duplicate of https://github.com/brave/brave-ios/issues/3183

**Closed as completed** 2021-03-19 12:57 UTC
Labels: closed/duplicate
