### ISSUE TITLE
Intermittently lose tabs and switch out of Private mode when Brave is in the background

### ISSUE THREAD

**Issue by MistakesHaveBeenMade** [brave/brave-ios#1091] opened 2019-05-16 00:27 UTC
### Description: 
Intermittently, after browsing the internet in private mode for a while and then putting Brave in the background, when I return to it I'm no longer in private browsing mode and I've lost all my open tabs.

To clarify, when I say "putting Brave in the background" I am not talking about killing the app (swiping up in iOS multitasking). My expectations would be different under those circumstances.

### Steps to Reproduce 
  1. Enter private browsing mode
  2. Browse the internet, opening several tabs to different sites (in my case, 3-5)
  3. Put Brave in the background (via home button or iOS multitasking)
  4. Switch back to Brave after ~5 minutes

**Actual result:** 
Brave is no longer in private browsing mode, switching back to private browsing shows there are no tabs open.

**Expected result:**
Brave is still in private browsing mode, previously opened tabs are still open.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent. Using Brave as my primary browser, this happens roughly once every 2 days. I have not been able to isolate circumstances where the issue is consistently reproducible.

**Brave Version:** 
Version 1.9.1 (19.04.02.12)

**Device details:** 
Apple iPhone 6 (MG4P2LL/A)
iOS 12.2

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### Additional Information

**Comment by MistakesHaveBeenMade** [comment] 2019-05-23 23:58
At this point, it's happening once or twice a day. Still no clear way to reproduce; some times when I open the app it's fine, other times my poor tabs are lost and gone forever.

**Comment by jhreis** [comment] 2019-06-25 16:11
Thanks for your patience on this. This is actually expected behavior based on the system we have.

Tabs in private mode are not stored to disk, they are solely saved in memory/RAM (e.g. not stored onto in a database or anything). When iOS decides to remove our app from memory, this is equivalent to "killing the app" (swiping up on task manager). At this point all of your tabs are removed from memory as well (since the app was).

The only way for us to prevent this is to write all of your private tabs to disk (like most other iOS browsers). We have decided against this from a privacy perspective.

If you go into private mode via the tab manager, this is not a sticky setting, and when the tab is removed from memory, you will be brought back into normal browsing mode. To prevent this there is a setting "Private Browsing Only" you can turn on. Additionally, this setting will naturally dump your tabs more frequently. 

If you want to persist your tabs, you should just browse in normal mode. I am closing this ticket, but feel free to continue the discussion if you have additional questions.

**Closed as completed by jhreis** 2019-06-25 16:11 UTC
Labels: won't have
