### ISSUE TITLE
Regression: Last visited folder view is not retained

### ISSUE THREAD

**Issue by parsd51** [brave/brave-ios#4770] opened 2021-12-23 05:53 UTC
### Description: 
URL bookmark regression of: https://github.com/brave/brave-ios/issues/3072

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Every time

**Brave Version:** 
1.33

**Device details:** 
Ipad Air 4, iPadOS 15.2

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by soner-yuksel** [comment] 2022-01-04 17:23
Closing this ticket as duplicate of https://github.com/brave/brave-ios/issues/4789

**Closed as completed by soner-yuksel** 2022-01-04 17:23 UTC
Labels: closed/duplicate
