### ISSUE TITLE
Illegible favorite site title text and context menu text in Private mode

### ISSUE THREAD

**Issue by rismanrp** [brave/brave-ios#2094] opened 2019-12-07 19:15 UTC
![163F7D0C-2FD7-4924-A82C-14178AD79546](https://user-images.githubusercontent.com/2027300/70379539-77760700-1960-11ea-9088-c712ca5e059f.jpeg)
![41B23F5B-622C-473D-B12E-39120F0D8529](https://user-images.githubusercontent.com/2027300/70379540-77760700-1960-11ea-88d3-9d1458e838db.png)

Device: iPhone SE, iOS 13.1.3

**Comment by srirambv** [comment] 2019-12-08 14:11
Dupe of #2059

**Closed as completed by srirambv** 2019-12-08 14:11 UTC
Labels: closed/duplicate
