### ISSUE TITLE
Lots of Constraint Warnings

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#1826] opened 2019-10-30 02:22 UTC
### Description: 

Currently there are a lot of warning logs revolving around constraint breakage / issues.

e.g.

```
"<NSAutoresizingMaskLayoutConstraint:0x6000007bd9a0 h=--& v=--& UIView:0x7f929100f170.midY == 0   (active)>",
"<NSAutoresizingMaskLayoutConstraint:0x6000007bd9f0 h=--& v=--& UIView:0x7f929100f170.height == 0   (active)>",
"<SnapKit.LayoutConstraint:0x60000005a9a0@BrowserViewController.swift#587 UIStackView:0x7f92910109b0.top == UILayoutGuide:0x600001d72300.top>",
"<SnapKit.LayoutConstraint:0x60000004b3c0@BrowserViewController.swift#861 UIView:0x7f9291000110.top == UIStackView:0x7f92910109b0.bottom>",
"<SnapKit.LayoutConstraint:0x60000004b4e0@BrowserViewController.swift#864 UIView:0x7f9291000110.bottom == UIView:0x7f929100f170.top>",
"<NSLayoutConstraint:0x600000737890 'UIViewSafeAreaLayoutGuide-top' V:|-(44)-[UILayoutGuide:0x600001d72300'UIViewSafeAreaLayoutGuide']   (active, names: '|':UIView:0x7f9291009ac0 )>"
```

This ticket should remain open and referenced in PRs that fix specific issues. This can be closed once all known launch constraints issues are solved.
(e.g. `Ref #1826: Fixed constraint caused by bottom toolbar.`)

### Steps to Reproduce 
  1. Launch Brave via Xcode
  2. Observe logs

### Test Plan

Since this is an ongoing ticket to a degree (although hopefully short-lived), I added QA/yes, not because there are super specific test to be done, but to make aware of potential layout regressions.

Given a quick glance at the logs most of the changes will revolve around the primary UI:
- Bottom toolbar
- Top toolbar
- Favorites
- Shields Panel
- Showing up keyboard on website's text fields

It would be good to run tests on a couple extra devices and test specifically to see if any of these break. Here is an example of a test run:

iPad:
- open Brave, verify all main menus are shown / not shown (iPad should _not_ have bottom toolbar, but top toolbar, stats, favorites, should all be visible)
- rotate device to landscape, re-check
- rotate device to portrait, re-check
- close app, re-open
- quit app, re-open
- test app in side-by-side mode

etc...

Again, no super specific things. Each PR should relate to specific UI areas, which will be given for QA to verify against (e.g. "I adjusted the constraints on the bottom toolbar, so please pay attention to see if this causes any issues).

**Actual result:** 

UI looks correct, but lots of breaking taking place. These should be isolated and dealt with as this can lead to unpredictable behaviors.

**Expected result:**

No warnings.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100%

**Brave Version:** 

1.12.1+

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment] 2019-10-30 12:43
Dupe of https://github.com/brave/brave-ios/issues/1803 :D

I have a PR open that fixes most things here https://github.com/brave/brave-ios/pull/1736

I'll close my ticket as this one has better description and test plan

**Comment by kylehickinson** [comment] 2019-11-11 16:55
Fixed in https://github.com/brave/brave-ios/pull/1736

**Closed as completed by kylehickinson** 2019-11-11 16:55 UTC
Labels: bug, QA Pass - iPhone X, QA/Yes, release-notes/exclude, QA Pass - iPhone, QA Pass - iPad, Epic: Cleanup

**Comment by srirambv** [comment] 2020-02-21 06:29
- Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.20.19)
- Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.20.19)
- Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.20.19)
- Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.20.19)
- Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.20.19)
