### ISSUE TITLE
white space at the top of the `Hamburger Settings` menu

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#6362] opened 2022-11-09 18:27 UTC
### Description: 

Remove the extra white space at the top of the `Hamburger Menu` on `iPads`. For some reason, there's a white space that's always at the top of the settings menu when initially tapping on the `Hamburger Menu`. However, if you go into any other settings and then go back to the `root` list, you'll notice that the white space is removed.

This has been around for a while so it's not a new regression but should be fixed.

### Steps to Reproduce 

  1. launch `1.44.1 (22.10.25.18)` and run through onboarding
  2. once you're done going through onboarding, tap on the `Hamburger Menu`
  3. you'll notice the white space at the very top which should be removed

**Actual result:** 

https://user-images.githubusercontent.com/2602313/200910988-0f518873-3d0a-4fd9-8487-dfd976d197c1.mp4

**Expected result:**

We should remove the white space as it's taking up for no reason. Doesn't seem to be used for anything.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases outlined above.

**Brave Version:** 

*  `1.44.1 (22.10.25.18)`

**Device details:** 

* `iPad Air (3rd Gen)` running `iOS 16` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

**Comment by kylehickinson** [comment] 2022-11-09 21:24
@kjozwiak I just tested this and reproduced on 1.44.1 (app store build) but couldn't reproduce after updating to 1.45 (testflight release build)

I'm going to close this and mark it as fixed as of 1.45 can you please re-test? I believe it was fixed by building with Xcode 14

**Closed as completed by kylehickinson** 2022-11-09 21:24 UTC
Labels: bug, QA Pass - iPhone X, QA/Yes, QA Pass - iPhone, QA Pass - iPad, Epic: Settings

**Comment by Uni-verse** [comment] 2022-11-09 23:08
Verified using version `1.45 (22.11.8.15)` on the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPads - iPadOS 16.x, 15.x

- Ensured white space is not shown in the hamburger menu right after onboarding is completed.

Example | Example
-|-
![IMG_4096](https://user-images.githubusercontent.com/17885425/200961352-73db1adc-56e2-4f3f-9c91-1655de9c6f31.PNG) | ![IMG_0774](https://user-images.githubusercontent.com/17885425/200961411-33a51add-366b-4f38-91ea-a0e6eb29fb93.PNG)
