### ISSUE TITLE
Cannot Set Brave Beta as iOS Default Browser

### ISSUE THREAD

**Issue by Ryan-Goldstein** [brave/brave-ios#4943] opened 2022-02-04 05:31 UTC
### Description: 
Brave Beta from TestFlight cannot be set as the iOS default browser.

### Steps to Reproduce 
  1. Install Brave Beta Version 1.36 (22.2.3.11) from TestFlight.
  2. Go to Settings > BraveBeta.
  3. There is no option there to set the default browser.

**Actual result:** 

![2744BCD7-6EFB-455D-9B89-9E0A0413EA3A](https://user-images.githubusercontent.com/8300089/152476824-efcc2a03-2fbb-4330-b166-0db687ccbcd0.png)

**Expected result:**

The App Store version can be set as the default:

![748BC98F-AA5E-467D-B0B5-389206F4B181](https://user-images.githubusercontent.com/8300089/152477037-10bc968c-cb24-4fa7-a4f3-a15879ec54fc.png)

**Reproduces how often:**

Always

**Brave Version:** 

Version 1.36 (22.2.3.11)

**Device details:** 

iPhone 13 Pro, iOS 15.4 Public Beta

**Website problems only:**

N/A

### Additional Information

Chrome Beta via TestFlight can be set as the iOS default browser, so I see no reason why Brave Beta wouldn’t also have that option.

**Comment by kylehickinson** [comment] 2022-02-04 05:55
Duplicate of https://github.com/brave/brave-ios/issues/4117

**Comment by kylehickinson** [comment] 2022-02-04 05:56
This is due to the way we publish Brave Beta (it is a separate app entirely, doesn't overwrite the live app), which hasn't been granted the browser entitlement by Apple.

**Closed as completed by kylehickinson** 2022-02-04 05:56 UTC
Labels: closed/duplicate
