### ISSUE TITLE
App crashes upon exiting Private Mode

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1353] opened 2019-08-08 20:06 UTC
### Description: 
App crashes upon exiting Private Mode

![Screen Shot 2019-08-08 at 1.01.52 PM.png](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/740a1693-eeca-4e9a-8b95-2ad1ed47b11e)

https://bravesoftware.slack.com/archives/C06UXF3KJ/p1565294784162600

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 
1.11

**Device details:** 
iOS 12.4

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment] 2019-08-08 23:47
Closing as duplicate of #1309 and already fixed too.

**Closed as completed by jhreis** 2019-08-08 23:47 UTC
Labels: closed/duplicate
