### ISSUE TITLE
[iOS] Search Engine Default Promo

### ISSUE THREAD

**Issue by timchilds** [brave/brave-ios#5386] opened 2022-05-25 21:44 UTC
**Spec**
https://bravesoftware.slack.com/archives/G01F4JUNXAQ/p1653579788550169?thread_ts=1653563424.060639&cid=G01F4JUNXAQ

**Comment by iccub** [comment] 2022-05-26 11:08
Duplicate of https://github.com/brave/brave-ios/issues/4437

**Closed as not planned by iccub** 2022-05-26 11:08 UTC
Labels: closed/duplicate
