### ISSUE TITLE
iPad constraints incorrect when reloading pages in landscape mode

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#6635] opened 2022-12-13 00:11 UTC
### Description: 
- Websites not rendering properly on iPads.

### Steps to Reproduce 
  1. Rotate to landscape.
  2. Go to amazon.com
  3. Open any link as a preview (long-press).
  4. Then hit Open in New Tab
  5. Close the tab.
  6. Refresh the page.
  7. Wait 3-5 seconds.
  8. Click on the URL bar.
  9. Submit the search (so the page does a FRESH load, and not load from cache).

**Actual result:** 
- iPad's WebView constraints has a height of 0 and ambiguous position.
![image](https://user-images.githubusercontent.com/1530031/207190069-a1f37222-64fc-4fe4-8e11-d4fb1084eb58.png)

**Expected result:**
- Should have a proper height, and page should render FULLY.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
- Intermittent Issue

**Brave Version:** 
- 1.46.x

**Device details:** 
- iPad (Any OS version)

**Comment by iccub** [comment] 2022-12-13 00:18
duplicate of https://github.com/brave/brave-ios/issues/6623

**Closed as not planned by iccub** 2022-12-13 00:18 UTC
Labels: closed/duplicate
