### ISSUE TITLE
Autofill of username on login fields on iOS using password manager does not work

### ISSUE THREAD

**Issue by snowbound** [brave/brave-ios#3447] opened 2021-03-22 14:56 UTC
## Description 
Unable to autofill username when using password manager like 1Password or Bitwarden

## Steps to Reproduce

   1. Install Bitwarden or 1Password and enable password manage as option for Password autofill on Password under settings on iOS
   2. Go to login to your amazon or gmail account
   3. Click on username

## Actual result:
Username is blank

## Expected result:
Clicking on username should raise a prompt on the virtual keyboard on iOS to select Password and then allow 1Password or Bitwarden to fill in the username field from the appropriate entry from the password manger's vault

## Reproduces how often: 
Happens every login with every website

## Brave version (info found on brave://version)
1.23.1 (21.2.24.16

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NO
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Yes

## Miscellaneous Information:
You have to use the iOS SHARE option to select Bitwarden or 1Password to fill in the Username field. Once you get to the password field the autofill occurs depending on whether you have enabled 1Password or Bitwarden as the option under Passwords in iOS Settings.

**Comment by snowbound** [comment] 2021-03-22 15:12
This apparently works as it should on Twitter, Facebook and Instagram yet it exhibits issues on Amazon and Gmail logins. From 1Password support "We can confirm we can reproduce this. Safari invokes iOS keyboard autofill on Amazon & Gmail, Brave does not and neither does Edge which provides it's own address book suggestion instead. This is likely a chromium for iOS filling issue on multi-page logins."

**Comment by Brave-Matt** [comment] 2021-06-07 19:48
+1 from Community:
https://community.brave.com/t/repost-since-autoclosed-mobile-ios-version-saved-logins-do-not-prompt-to-populate-saved-login-information-on-pages-where-login-information-has-been-saved-in-brave-s-saved-logins-on-sites-with-separated-user-and-password-pages-amazon-com-1-is-an-exampl/257209/3

**Comment by ashutoshsaboo** [comment] 2022-07-23 17:26
+1 on this, any update on this? This is painful to copy paste login info manually on ios.

**Comment by mshddev** [comment] 2022-11-07 16:51
looking forward to this one

**Comment by georgebalt** [comment] 2022-11-30 03:15
Can confirm same issue on iPadOS 16

**Comment by A-t-s-u-s-h-i** [comment] 2023-03-24 01:01
i got some reports for this on AppStore review.

**Comment by mat926** [comment] 2023-03-28 02:49
Any updates on this?

**Comment by sumsumcity** [comment] 2023-05-07 09:45
Can someone please fix the problem?

**Comment by snowbound** [comment] 2023-05-07 14:45
Sigh. If this bug is still happening after 2+ years, I will have to let a 8 month old Brave bug with the Youtube chat  I reported back in Sept 2022 mellow for another couple of years.

**Comment by finnless** [comment] 2023-05-08 02:25
I believe this is a duplicate of brave/brave-browser#36028

**Comment by kylehickinson** [comment] 2023-05-10 18:53
I believe I've explained this in the past when this bug was originally surfaced but this is unfortunately not possible for us to fix. The problem lies within Apple's implementation of this auto-fill feature within `WKWebView` (the web view component we have to use in Brave iOS). Safari unfortunately gets a more feature complete version that we don't have access to; like showing usernames in the keyboard, as well as displaying the password button when focused on a username field.

This has been brought up to Apple before in the past (one bug report I can find for instance: https://bugs.webkit.org/show_bug.cgi?id=203299). Third-party browsers unfortunately do not have any control over the system auto-fill feature or how it integrates with websites in the browser.

**Closed as not planned by kylehickinson** 2023-05-10 18:53 UTC
Labels: closed/not-actionable

**Comment by dlinah** [comment] 2023-09-23 14:37
@kylehickinson how about making the login option easily accessible in the top bar for the current website , the only solution right now is to do 4/5 steps to get the password from the menu
