### ISSUE TITLE
Unable to save Gif images on iOS 12

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2790] opened 2020-08-06 06:35 UTC
### Description: 
Unable to save Gif images on iOS 12

### Steps to Reproduce 
  1. Search for funny gif 
  2. Open a gif image
  3. Long press to save image, save one frame instead of the gif image

**Actual result:** 
Unable to save Gif images on iOS 12

**Expected result:**
Should be able to save gif image 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.19 / 1.19.1

**Device details:** 
iPad and iPhone running iOS 12 only

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
Found while testing https://github.com/brave/brave-ios/issues/2778

**Comment by iccub** [comment] 2020-08-06 09:19
This is broken on 1.19 too?

**Comment by srirambv** [comment] 2020-08-06 09:53
Yup

**Comment by iccub** [comment] 2020-08-06 10:04
let's move to 1.21

**Comment by soner-yuksel** [comment] 2021-02-01 16:33
The problem is  there is only 2 way to save a photo into Photo Album < iOS 12.
First is `UIImageWriteToSavedPhotosAlbum` and other one is `PHPhotoLibrary`.

- Saving with `UIImageWriteToSavedPhotosAlbum()` call, which takes an UIImage object as parameter. The problem here is that because the image must be an UIImage, you can no longer save the original photo metadata data. The file format, animations for GIFs and all metadata will be lost. This is what happening to us here.

- The other one is using `PHPhotoLibrary` and creating an Asset to save in Photos works properly however we have to use `NSPhotoLibraryUsageDescription` instead of `NSPhotoLibraryAddUsageDescription`. 
However we cant use `NSPhotoLibraryUsageDescription` as per default browser requirements:
https://developer.apple.com/documentation/xcode/allowing_apps_and_websites_to_link_to_your_content/preparing_your_app_to_be_the_default_browser_or_email_client

We have to dig deeper to solve this problem and it is possible there is no solution to it at this point. because of limitations and iOS 12 requirements.
For this reason moving this ticket out of 1.23.

**Comment by kylehickinson** [comment] 2021-05-06 16:14
iOS 12 no longer supported

**Closed as completed by kylehickinson** 2021-05-06 16:14 UTC
Labels: closed/invalid
