### ISSUE TITLE
Brave iOS 1.33 bookmarks no longer remembers previous location

### ISSUE THREAD

**Issue by sinner-** [brave/brave-ios#4818] opened 2022-01-09 11:39 UTC
### Description: 
In previous versions of Brave iOS when you tapped the bookmarks button it would return you to whichever folder you had previously been in.

As of the most recent update (1.33), tapping the bookmarks button takes you to the root bookmarks folder, in my case it's a single item titled "Mobile Bookmarks" which I have to tap again every time to tap an actual bookmark

### Steps to Reproduce 
  1. Tap the bookmarks button
 
Bookmark menu shows the root directory

**Expected result:**
Bookmark menu shows the bookmark folder you were previously navigated to, i.e. "Mobile Bookmarks"

**Reproduces how often:**
Easily Reproduced

**Brave Version:** 
1.33 (21.12.14.16)

**Device details:** 
iPhone SE 1 iOS 15.2

**Comment by iccub** [comment] 2022-01-09 16:05
Closing as duplicate of https://github.com/brave/brave-ios/issues/4789

**Closed as completed by iccub** 2022-01-09 16:05 UTC
Labels: closed/duplicate
