### ISSUE TITLE
[Feature Request] Ability to move the search bar to the bottom on iOS

### ISSUE THREAD

**Issue by TaxingAuthority** [brave/brave-ios#5183] opened 2022-03-30 20:38 UTC
Safari on iOS moved the search bar to the bottom of the screen which ended up helping navigation. I noticed Firefox on iOS recently released the ability to also move the search bar to the bottom.

Would it be possible to add this functionality to the Brave on iOS as well?

**Comment by kylehickinson** [comment] 2022-03-30 21:43
Hi @TaxingAuthority, we are looking into this for future updates.

**Comment by kylehickinson** [comment] 2022-03-30 21:44
Duplicate of https://github.com/brave/brave-ios/issues/4002

**Closed as completed by kylehickinson** 2022-03-30 21:44 UTC
Labels: closed/duplicate
