### ISSUE TITLE
Sometimes, the Default Browser callout appears before the VPN callout

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#4719] opened 2021-12-11 07:06 UTC
### Description: 

Sometimes, the Default Browser callout appears before the VPN callout

### Steps to Reproduce 
1. fresh install Brave `1.33 (21.12.10.20)` from TestFlight (`production` channel, orange logo)
2. launch Brave
3. tap `Let's go` on the `Privacy made easy` screen
4. tap `Not now`
5. tap `Skip`
4. tap to clear 1st tour slide
5. tap again to clear 2nd tour slide
6. force-quit/close Brave
7. adjust your iOS date to 12 days in advance or rent a Dolorean
8. force-quit the `Settings` app
9. launch Brave again
10. keep trying the above steps until you see the `Default browser` callout, instead of the `Brave Firewall + VPN`, which should be *first*
11. now notice you'll get `Brave Firewall and VPN` callout (at least in US)
`...`
12. notice Rewards callout
13. force-quit
14. notice Sync callout

Actual | Expected
-------|----------
<video src="https://user-images.githubusercontent.com/387249/145667586-f5e898ac-ef22-453d-912c-abe92a5b9a89.MP4"> | <video src="https://user-images.githubusercontent.com/387249/145667843-30dc21ef-f349-4630-a4e6-6c41173b247f.MP4">

**Actual result:** 

Sometimes, the Default Browser callout appears before the VPN callout

**Expected result:**

Conferring with folks, it seems VPN should always be offered first (assuming these steps with 10+ days, per spec)

Case 5, here: `https://github.com/brave/brave-ios/issues/4376#issuecomment-990086624`

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Not 100%, but often enough

**Brave Version:** 

`1.33 (21.12.10.20)`

**Device details:** 

Reproduces for me on two iPhone 6s, 1) `iOS 14.4.2` and 2) `15.0.2`

@brave/legacy_qa

**Comment by stephendonner** [comment] 2021-12-11 07:17
Cross-reference: https://github.com/brave/brave-ios/issues/4682

**Comment by LaurenWags** [comment] 2021-12-13 15:23
Reproduced multiple times with https://github.com/brave/brave-ios/issues/4376#issuecomment-992539850.

Seems to be if number of days  = 10, call out order is as expected. If number of days > 10, callout is out of order.

**Comment by GeetaSarvadnya** [comment] 2021-12-13 17:19
As per the slack thread explanation, closing the issue https://bravesoftware.slack.com/archives/C06UXF3KJ/p1639415370235300?thread_ts=1639310900.218900&cid=C06UXF3KJ

**Closed as completed** 2021-12-13 18:20 UTC
Labels: closed/wontfix
