### ISSUE TITLE
App Bookmark button on iPad

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1381] opened 2019-08-12 16:36 UTC
### Description: 
Please add an option for users on the iPad to open Bookmarks with one tap.

Potentially add a Bookmark button on the top menu, beside the URL bar as Safari does on the iPad. 

Internal Chat: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1565356907167000

@jamesmudgett can you please create a design?

**Comment by iccub** [comment] 2019-08-12 16:39
Duplicate of https://github.com/brave/brave-ios/issues/1323

**Comment by iccub** [comment] 2019-08-12 16:40
Reopening, but this is v similar to https://github.com/brave/brave-ios/issues/1323

we might want to merge that into one ticket

**Comment by anthonypkeane** [comment] 2019-08-12 22:27
This is a short term fix to add a bookmark icon to the iPad to open bookmarks

We can use the icon from https://github.com/brave/brave-ios/issues/1323 

Unlike https://github.com/brave/brave-ios/issues/1323, this issue does not have potentially new bookmark UI

**Comment by anthonypkeane** [comment] 2019-08-28 22:02
same icon as https://github.com/brave/brave-ios/issues/1391

**Comment by jhreis** [comment] 2019-08-29 00:17
Closing per: https://github.com/brave/brave-ios/issues/1391

**Closed as completed by jhreis** 2019-08-29 00:17 UTC
Labels: closed/duplicate, QA/Yes, release-notes/include, feature-request
