### ISSUE TITLE
Update error message when passcode is entered incorrectly 3 times

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#937] opened 2019-03-03 22:29 UTC
### Description: 

Add description about timeout after maximum attempts are reached for passcode.

![image](https://user-images.githubusercontent.com/1903815/53702850-50324e00-3dc0-11e9-98ff-ccee02854ee8.png)

### Steps to Reproduce 
  1.  Enable passcode for Brave
  2. Enter incorrect passcode 3 times

**Actual result:** 
Error code shows: Maximum attempts reached. Please try again later

**Expected result:**
Update error to display timeout when user enters a passcode incorrectly 3 times.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
v 1.7.4

**Device details:** 
iPhone SE (iOS 12.1.4)

**Comment by kylehickinson** [comment] 2019-03-04 01:14
Duplicate of #443

**Closed as completed by kylehickinson** 2019-03-04 01:14 UTC
Labels: closed/duplicate
