### ISSUE TITLE
 Brave crashes when brave is restarted 3 to 4 times

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#4700] opened 2021-12-10 07:56 UTC
### Description: 

@kjozwiak Found a crash issue in the latest TF version 1.33. Filing an issue on behalf of @kjozwiak 

 Brave crashes when brave is restarted 3 to 4 times

### Steps to Reproduce 
  1. Clean profile 1.33 (21.12.9.23)
  2. Skip the welcome onboarding flow
  3. Restart brave 3 to 4 times
  4. Brave crashes

**Actual result:** 
 Brave crashes when brave is restarted 3 to 4 times

**Expected result:**
Should not be any crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.33 (21.12.9.23)

**Device details:** 
iPad 7th Generation - iOS 15.1

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T @soner-yuksel 

The issue is Reproduced  by @anthonypkeane and @GeetaSarvadnya

**Comment by kjozwiak** [comment] 2021-12-13 17:32
Closing as this has been addressed via https://github.com/brave/brave-ios/pull/4717 and verified by QA via https://github.com/brave/brave-ios/issues/4716#issuecomment-991367774. @GeetaSarvadnya also mentioned that she can't reproduce the original issue anymore.

**Closed as completed by kjozwiak** 2021-12-13 17:32 UTC
Labels: closed/duplicate
