### ISSUE TITLE
Brave crash when bookmark or delete

### ISSUE THREAD

**Issue by Justin2997** [brave/brave-ios#3197] opened 2021-01-13 01:09 UTC
### Description: 
When you try to delete a bookmark by sliding on the left and click on delete, the app close and crash.

### Steps to Reproduce 
  1. Open brave
  2. Go in a bookmark list
  3. Slide to delete and click

**Actual result:** 

**Expected result:**
Not crashing

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

Version 1.22.1 (20.12.10.23) Appareil iPhone11,8 (iOS 14.0)

**Device details:** 
iPhone XR

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

**Comment by iccub** [comment] 2021-01-13 16:27
Thanks for the report, we want to fix it in next release,
closing as duplicate of https://github.com/brave/brave-ios/issues/3194

**Closed as completed by iccub** 2021-01-13 16:27 UTC
Labels: closed/duplicate
