### ISSUE TITLE
Default Load Websites in Desktop Mode

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#810] opened 2019-01-28 17:53 UTC
### Description: 

Mostly useful for iPad users who want to browse the web in "desktop" mode, more than mobile mode. This is a feature in Android.

From [community](https://community.brave.com/t/desktop-site-by-default-option/43194/2).

**Comment by iccub** [comment] 2019-01-28 22:17
Duplicate of https://github.com/brave/brave-ios/issues/804 :)

**Closed as completed by iccub** 2019-01-28 22:17 UTC
Labels: closed/duplicate
