### ISSUE TITLE
Setting for auto closing tabs when not saw during a defined time

### ISSUE THREAD

**Issue by Hydrog3n** [brave/brave-ios#3007] opened 2020-11-03 21:47 UTC
Hello, Thank you for Developing this Browser <3 

## Problem Description 
When we use Brave in iOS all the day tab starts to accumulate and sometimes I look at the number of tabs I have it's crazy. ~200.
An option in the settings should be added to select if we want of not and the delays. Safari has this feature. 
## Feature Overview 
When this feature has enabled all tabs not watch/display during a defined time should be closed.

**Comment by iccub** [comment] 2020-11-03 21:52
Thanks for the report, we want to have it at some point
Closing as a duplicate of https://github.com/brave/brave-ios/issues/1514

**Closed as completed by iccub** 2020-11-03 21:52 UTC
Labels: closed/duplicate

**Comment by Hydrog3n** [comment] 2020-11-03 22:12
Oh sorry I didn't found this issue. Thank I will follow it.
