### ISSUE TITLE
Brave's 404 or WebKitErrorDomain page

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#678] opened 2019-01-07 18:09 UTC
### Description: 
Redesign the WebKitErrorDomain page to that is

- looks better
- gives more information to the user

![Screen Shot 2019-01-07 at 10.07.21 AM.png](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/816231d7-6bb5-40a2-ae17-298851003cca)

For ideas look at https://www.creativebloq.com/web-design/best-404-pages-812505

**Comment by kylehickinson** [comment] 2019-01-08 16:00
Isn't this a dupe of #650 (which is a dupe of #317)?

**Comment by anthonypkeane** [comment] 2019-01-08 19:02
actually correct, it is. I'll close it @kylehickinson

**Comment by anthonypkeane** [comment] 2019-01-08 19:03
dupe of #650

**Closed as completed** 2019-01-08 19:02 UTC
