### ISSUE TITLE
Remove tracking info after the ? on Twitter URL's on copy/paste

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#6382] opened 2022-11-11 22:09 UTC
### Description: 
Slack: https://bravesoftware.slack.com/archives/G15HNQKV5/p1668204169387939?thread_ts=1668184399.002919&cid=G15HNQKV5

Please remove the tracking info by default on Twitter URL's (i.e ?s=20&t=<tracking-id>) when a user copies and pastes the link

**Comment by iccub** [comment] 2022-11-23 19:20
Duplicate of the general 'clean copy url' project
https://github.com/brave/brave-ios/issues/6382

**Closed as not planned by iccub** 2022-11-23 19:20 UTC
Labels: closed/duplicate
