### ISSUE TITLE
Sample ad notification for Brave Rewards appears in vertically middle rather than vertically top

### ISSUE THREAD

**Issue by yachtcaptain23** [brave/brave-ios#1794] opened 2019-10-24 21:51 UTC
### Steps to Reproduce 
  1. Install Brave
  2. Go through OOBE and turn on ads
  3. Default notification appears in the middle of the screen at the top of the popup panel

**Actual result:** 
 Default notification appears in the middle of the screen at the top of the popup panel

**Expected result:**
Appears at the top of the screen

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 
iPadOS 13.1.2

**Website problems only:**
- did you check with Brave Shields down? No
- did you check in Safari/Firefox (WkWebView-based browsers)? No

**Comment by Brandon-T** [comment] 2019-10-28 17:46
**Implementation:**

![image](https://user-images.githubusercontent.com/1530031/67703062-3108b200-f989-11e9-9bb1-aee8d7fcd450.png)


**Design:**

![image](https://user-images.githubusercontent.com/1530031/67703082-3960ed00-f989-11e9-999f-581f3eba1fed.png)

Is it wrong or? Because I did it exactly how I was told :S

**Comment by kylehickinson** [comment] 2019-10-28 17:48
I think this is expected, @karenkliu can confirm

**Comment by karenkliu** [comment] 2019-10-28 23:53
haha aw. Yeah, this is correct for now.
 
I think when we update this onboarding with iPad-specific graphics though we'll want to have an ad notification that looks more iPad native.

**Comment by kylehickinson** [comment] 2019-10-29 13:27
As per Karen, going to close this for now as expected behaviour. Will revisit in a future iPad-specific onboarding updates ticket

**Closed as completed by kylehickinson** 2019-10-29 13:27 UTC
Labels: Epic: Rewards
