### ISSUE TITLE
Provide an option to allow user to persistent tabs in private mode 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3835] opened 2021-06-22 22:06 UTC
### Description: 
Please provide an option to allows users to persistent tabs in private mode

Under Display
Persistent Tabs in Private Mode (On/Off)
Default = Off (as we do today)

@jamesmudgett for review before implementation can begin
@jumde for comment as we may need a security review here

**Comment by iccub** [comment] 2022-02-16 20:43
duplicate of https://github.com/brave/brave-ios/issues/3183

**Closed as completed by iccub** 2022-02-16 20:43 UTC
Labels: closed/duplicate
