### ISSUE TITLE
Dropped transactions are never retired in our Wallet

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#5023] opened 2022-02-24 14:56 UTC
Same issue as seen on Desktop and Android https://github.com/brave/brave-browser/issues/21051

We need to find a better way to communicate the following:

- A pending transaction that is not going through (gas issue) is likely to prevent future send transactions from going through.
- The failing pending transaction needs to be cancelled before a new one may be sent, or it will need to be completed.

## Solution

Query the pending "submitted" transactions from the account which is trying to perform a new send during the validation checks. Update the messaging and link to pending list, something like, "We have detected a pending transaction that has not yet completed and will prevent this transaction from executing. View pending transactions"

**Comment by jamesmudgett** [comment] 2022-02-24 18:07
Will need to also query that the "Submitted" transaction are > 1day old (24hr)
![Screen Shot 2022-02-24 at 11 50 06 AM](https://user-images.githubusercontent.com/318119/155582034-afea59bf-ddf7-4678-9aa1-e6efb0df1bf1.png)

**Comment by bbondy** [comment] 2022-02-24 20:09
To clarify: If any "Submitted" transaction exists > 1 day old.

**Comment by bbondy** [comment] 2022-02-25 01:04
***That have not confirmed

**Comment by iccub** [comment] 2022-02-26 00:00
Copy from this ticket comment will be used https://github.com/brave/brave-browser/issues/21051#issuecomment-1051233983

**Comment by nuo-xu** [comment] 2022-03-03 15:42
we have an known issue that [OnTransactionStatusChanged Observer not Firing for Confirmed Transactions](https://github.com/brave/brave-browser/issues/21300)

**Comment by nuo-xu** [comment] 2024-03-08 17:47
Close this issue since we have now handle transaction status `Dropped` updated from core. And a work around to pass that tx by editing nonce #

**Closed as completed by nuo-xu** 2024-03-08 17:47 UTC
Labels: bug, QA/Yes, Epic: Brave Wallet
