### ISSUE TITLE
Add support for Apple Pay

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2990] opened 2020-10-22 18:06 UTC
### Description: 
Slack Thread: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1603216841312500

Please add support for Apple Pay in Brave.

**Comment by kylehickinson** [comment] 2020-10-22 19:23
duplicate of https://github.com/brave/brave-ios/issues/2985

**Closed as completed by kylehickinson** 2020-10-22 19:23 UTC
Labels: closed/duplicate
