### ISSUE TITLE
Application crash browse website

### ISSUE THREAD

**Issue by dodieboy** [brave/brave-ios#4967] opened 2022-02-09 11:58 UTC
### Description: 
Brave browser for ios crash whenever I try to browse to any website after updating to this version

### Steps to Reproduce 
  1.open brave browser ios
  2.enter any website 
  3.application crash

**Actual result:** 
https://streamable.com/667m77

**Expected result:**
No crashes 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily 

**Brave Version:** 
V1.35 (22.2.4.17)

**Device details:** 
Iphone 12 Pro IOS 14.1

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

**Comment by iccub** [comment] 2022-02-09 12:46
Thanks for report @dodieboy,
do you have sync enabled?
do you have Brave Rewards enabled?

I tested on my iphone 8 with iOS 14.8.1 and I can't seem to reproduce it

**Comment by dodieboy** [comment] 2022-02-09 12:47
Brave reward is disabled, sync bookmark is enabled, sync history is disabled

**Comment by iccub** [comment] 2022-02-09 12:50
@dodieboy  can you check it with disabled sync?
does it matter whether you enter a url manually or visit a top site?

I'm trying to narrow down the problem, could be this specific iOS 14.1 crash, we are still waiting for crashlogs to show up

**Comment by dodieboy** [comment] 2022-02-09 12:53
The application crash both using top site and manual keying of website, even click the report bug from the menu.
Tried disable sync, it still crash

**Comment by dodieboy** [comment] 2022-02-09 12:55
I also tried disable brave shield, it still crash

**Comment by iccub** [comment] 2022-02-09 12:58
@dodieboy if you have diagnostic usage enabled on iPhone can you try retrieving crash logs from your device?
You can follows steps from here https://help.dropbox.com/installs-integrations/mobile/ios-crash-logs#iphone

In the `Diagnostic & Usage Data` you have to look for `Client.app` entry, this is how our app is named if it does not show up as Brave. 
If you are able to post it here that could help us resolving it quickly

**Comment by dodieboy** [comment] 2022-02-09 13:08
{"app_name":"Client","timestamp":"2022-02-09 21:01:56.00 +0800","app_version":"1.35","slice_uuid":"","adam_id":1052879175,"build_version":"22.2.4.17","platform":2,"bundleID":"com.brave.ios.browser","share_with_app_devs":0,"is_first_party":0,"bug_type":"109","os_version":"iPhone OS 14.1 (18A8395)","incident_id":"1B21FE1E-97D4-49F9-BCFF-9AD9866FEF02","name":"Client"}
Incident Identifier: 1B21FE1E-97D4-49F9-BCFF-9AD9866FEF02
CrashReporter Key:   1f8b26d76b988bd894060b1792a28119274bbe31
Hardware Model:      iPhone13,3
Process:             Client [231]
Path:                /private/var/containers/Bundle/Application/1BDE3F59-3E1E-42F5-B85E-2DAEC20459F0/Client.app/Client
Identifier:          com.brave.ios.browser
Version:             22.2.4.17 (1.35)
AppStoreTools:       13C90b
AppVariant:          1:iPhone13,3:14
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.brave.ios.browser [367]


Date/Time:           2022-02-09 21:01:55.8415 +0800
Launch Time:         2022-02-09 21:01:51.2479 +0800
OS Version:          iPhone OS 14.1 (18A8395)
Release Type:        User
Baseband Version:    1.00.03-5
Report Version:      104

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x0000000192234730
Termination Signal: Trace/BPT trap: 5
Termination Reason: Namespace SIGNAL, Code 0x5
Terminating Process: exc handler [231]
Triggered by Thread:  0

Thread 0 name:  CrWebMain  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libswiftCore.dylib            	0x0000000192234730 0x1921fe000 + 223024
1   libswiftCore.dylib            	0x0000000192234730 0x1921fe000 + 223024
2   libswiftWebKit.dylib          	0x00000001d64521d4 0x1d6450000 + 8660
3   libswiftWebKit.dylib          	0x00000001d6452314 0x1d6450000 + 8980
4   libswiftWebKit.dylib          	0x00000001d6451a68 0x1d6450000 + 6760
5   WebKit                        	0x000000019a977c38 0x19a725000 + 2436152
6   WebKit                        	0x000000019aa63f4c 0x19a725000 + 3403596
7   WebKit                        	0x000000019aa71e48 0x19a725000 + 3460680
8   WebKit                        	0x000000019aa71cbc 0x19a725000 + 3460284
9   WebKit                        	0x000000019ad2dc3c 0x19a725000 + 6327356
10  WebKit                        	0x000000019a7721a8 0x19a725000 + 315816
11  WebKit                        	0x000000019aa93958 0x19a725000 + 3598680
12  WebKit                        	0x000000019a755d78 0x19a725000 + 200056
13  WebKit                        	0x000000019a755680 0x19a725000 + 198272
14  JavaScriptCore                	0x00000001986ed324 0x19788e000 + 15069988
15  JavaScriptCore                	0x00000001986edf24 0x19788e000 + 15073060
16  CoreFoundation                	0x000000018e67f81c 0x18e5e1000 + 649244
17  CoreFoundation                	0x000000018e67f718 0x18e5e1000 + 648984
18  CoreFoundation                	0x000000018e67ea28 0x18e5e1000 + 645672
19  CoreFoundation                	0x000000018e678d20 0x18e5e1000 + 621856
20  CoreFoundation                	0x000000018e6784bc 0x18e5e1000 + 619708
21  GraphicsServices              	0x00000001a518a820 0x1a5187000 + 14368
22  UIKitCore                     	0x0000000191025164 0x1904a6000 + 12054884
23  UIKitCore                     	0x000000019102a840 0x1904a6000 + 12077120
24  Client                        	0x00000001009d3e8c 0x100964000 + 458380
25  libdyld.dylib                 	0x000000018e33fe40 0x18e33f000 + 3648

Thread 1:
0   libsystem_pthread.dylib       	0x00000001d65fa774 0x1d65f0000 + 42868

Thread 2:
0   libsystem_pthread.dylib       	0x00000001d65fa774 0x1d65f0000 + 42868

Thread 3:
0   libsystem_pthread.dylib       	0x00000001d65fa774 0x1d65f0000 + 42868

Thread 4 name:  com.apple.uikit.eventfetch-thread
Thread 4:
0   libsystem_kernel.dylib        	0x00000001ba840dd0 0x1ba83d000 + 15824
1   libsystem_kernel.dylib        	0x00000001ba840184 0x1ba83d000 + 12676
2   CoreFoundation                	0x000000018e67ecf8 0x18e5e1000 + 646392
3   CoreFoundation                	0x000000018e678ea8 0x18e5e1000 + 622248
4   CoreFoundation                	0x000000018e6784bc 0x18e5e1000 + 619708
5   Foundation                    	0x000000018f8f9e30 0x18f8f2000 + 32304
6   Foundation                    	0x000000018f8f9d08 0x18f8f2000 + 32008
7   UIKitCore                     	0x00000001910d5a4c 0x1904a6000 + 12778060
8   Foundation                    	0x000000018fa640f0 0x18f8f2000 + 1515760
9   libsystem_pthread.dylib       	0x00000001d65f1ca8 0x1d65f0000 + 7336
10  libsystem_pthread.dylib       	0x00000001d65fa788 0x1d65f0000 + 42888

Thread 5:
0   libsystem_pthread.dylib       	0x00000001d65fa774 0x1d65f0000 + 42868

Thread 6 name:  Dispatch queue: com.apple.libnetwork.pacResolution
Thread 6:
0   libsystem_kernel.dylib        	0x00000001ba840dd0 0x1ba83d000 + 15824
1   libsystem_kernel.dylib        	0x00000001ba840184 0x1ba83d000 + 12676
2   CoreFoundation                	0x000000018e67ecf8 0x18e5e1000 + 646392
3   CoreFoundation                	0x000000018e678ea8 0x18e5e1000 + 622248
4   CoreFoundation                	0x000000018e6784bc 0x18e5e1000 + 619708
5   libnetwork.dylib              	0x000000018f2aba08 0x18f17f000 + 1231368
6   libdispatch.dylib             	0x000000018e2fefd0 0x18e2fd000 + 8144
7   libdispatch.dylib             	0x000000018e300ac8 0x18e2fd000 + 15048
8   libdispatch.dylib             	0x000000018e307c08 0x18e2fd000 + 44040
9   libdispatch.dylib             	0x000000018e308768 0x18e2fd000 + 46952
10  libdispatch.dylib             	0x000000018e312528 0x18e2fd000 + 87336
11  libsystem_pthread.dylib       	0x00000001d65f3908 0x1d65f0000 + 14600
12  libsystem_pthread.dylib       	0x00000001d65fa77c 0x1d65f0000 + 42876

Thread 7:
0   libsystem_pthread.dylib       	0x00000001d65fa774 0x1d65f0000 + 42868

Thread 8 name:  NetworkConfigWatcher
Thread 8:
0   libsystem_kernel.dylib        	0x00000001ba840dd0 0x1ba83d000 + 15824
1   libsystem_kernel.dylib        	0x00000001ba840184 0x1ba83d000 + 12676
2   CoreFoundation                	0x000000018e67ecf8 0x18e5e1000 + 646392
3   CoreFoundation                	0x000000018e678ea8 0x18e5e1000 + 622248
4   CoreFoundation                	0x000000018e6784bc 0x18e5e1000 + 619708
5   Foundation                    	0x000000018f8f9e30 0x18f8f2000 + 32304
6   BraveCore                     	0x0000000102fb8c74 0x102448000 + 11996276
7   BraveCore                     	0x0000000102fb7a98 0x102448000 + 11991704
8   BraveCore                     	0x0000000102f8558c 0x102448000 + 11785612
9   BraveCore                     	0x0000000102f5c66c 0x102448000 + 11617900
10  BraveCore                     	0x0000000102f9cc30 0x102448000 + 11881520
11  BraveCore                     	0x0000000102f9cdac 0x102448000 + 11881900
12  BraveCore                     	0x0000000102fb3370 0x102448000 + 11973488
13  libsystem_pthread.dylib       	0x00000001d65f1ca8 0x1d65f0000 + 7336
14  libsystem_pthread.dylib       	0x00000001d65fa788 0x1d65f0000 + 42888

Thread 9 name:  ThreadPoolServiceThread
Thread 9:
0   libsystem_kernel.dylib        	0x00000001ba840dd0 0x1ba83d000 + 15824
1   libsystem_kernel.dylib        	0x00000001ba840184 0x1ba83d000 + 12676
2   CoreFoundation                	0x000000018e67ecf8 0x18e5e1000 + 646392
3   CoreFoundation                	0x000000018e678ea8 0x18e5e1000 + 622248
4   CoreFoundation                	0x000000018e6784bc 0x18e5e1000 + 619708
5   Foundation                    	0x000000018f8f9e30 0x18f8f2000 + 32304
6   BraveCore                     	0x0000000102fb8c74 0x102448000 + 11996276
7   BraveCore                     	0x0000000102fb7a98 0x102448000 + 11991704
8   BraveCore                     	0x0000000102f8558c 0x102448000 + 11785612
9   BraveCore                     	0x0000000102f5c66c 0x102448000 + 11617900
10  BraveCore                     	0x0000000102f9cc30 0x102448000 + 11881520
11  BraveCore                     	0x0000000102f8e6bc 0x102448000 + 11822780
12  BraveCore                     	0x0000000102f9cdac 0x102448000 + 11881900
13  BraveCore                     	0x0000000102fb3370 0x102448000 + 11973488
14  libsystem_pthread.dylib       	0x00000001d65f1ca8 0x1d65f0000 + 7336
15  libsystem_pthread.dylib       	0x00000001d65fa788 0x1d65f0000 + 42888

Thread 10 name:  ThreadPoolForegroundWorker
Thread 10:
0   libsystem_kernel.dylib        	0x00000001ba840dd0 0x1ba83d000 + 15824
1   libsystem_kernel.dylib        	0x00000001ba840184 0x1ba83d000 + 12676
2   BraveCore                     	0x0000000102fba7d8 0x102448000 + 12003288
3   BraveCore                     	0x0000000102f96a00 0x102448000 + 11856384
4   BraveCore                     	0x0000000102f97434 0x102448000 + 11858996
5   BraveCore                     	0x0000000102f97004 0x102448000 + 11857924
6   BraveCore                     	0x0000000102fb3370 0x102448000 + 11973488
7   libsystem_pthread.dylib       	0x00000001d65f1ca8 0x1d65f0000 + 7336
8   libsystem_pthread.dylib       	0x00000001d65fa788 0x1d65f0000 + 42888

Thread 11 name:  ThreadPoolBackgroundWorker
Thread 11:
0   libsystem_kernel.dylib        	0x00000001ba840dd0 0x1ba83d000 + 15824
1   libsystem_kernel.dylib        	0x00000001ba840184 0x1ba83d000 + 12676
2   BraveCore                     	0x0000000102fba7d8 0x102448000 + 12003288
3   BraveCore                     	0x0000000102f96a00 0x102448000 + 11856384
4   BraveCore                     	0x0000000102f97434 0x102448000 + 11858996
5   BraveCore                     	0x0000000102f96f80 0x102448000 + 11857792
6   BraveCore                     	0x0000000102fb3370 0x102448000 + 11973488
7   libsystem_pthread.dylib       	0x00000001d65f1ca8 0x1d65f0000 + 7336
8   libsystem_pthread.dylib       	0x00000001d65fa788 0x1d65f0000 + 42888

Thread 12 name:  ThreadPoolBackgroundWorker
Thread 12:
0   libsystem_kernel.dylib        	0x00000001ba840dd0 0x1ba83d000 + 15824
1   libsystem_kernel.dylib        	0x00000001ba840184 0x1ba83d000 + 12676
2   BraveCore                     	0x0000000102fba7d8 0x102448000 + 12003288
3   BraveCore                     	0x0000000102f96a00 0x102448000 + 11856384
4   BraveCore                     	0x0000000102f97434 0x102448000 + 11858996
5   BraveCore                     	0x0000000102f96f80 0x102448000 + 11857792
6   BraveCore                     	0x0000000102fb3370 0x102448000 + 11973488
7   libsystem_pthread.dylib       	0x00000001d65f1ca8 0x1d65f0000 + 7336
8   libsystem_pthread.dylib       	0x00000001d65fa788 0x1d65f0000 + 42888

Thread 13 name:  Web_IOThread
Thread 13:
0   libsystem_kernel.dylib        	0x00000001ba840dd0 0x1ba83d000 + 15824
1   libsystem_kernel.dylib        	0x00000001ba840184 0x1ba83d000 + 12676
2   CoreFoundation                	0x000000018e67ecf8 0x18e5e1000 + 646392
3   CoreFoundation                	0x000000018e678ea8 0x18e5e1000 + 622248
4   CoreFoundation                	0x000000018e6784bc 0x18e5e1000 + 619708
5   Foundation                    	0x000000018f8f9e30 0x18f8f2000 + 32304
6   BraveCore                     	0x0000000102fb8c74 0x102448000 + 11996276
7   BraveCore                     	0x0000000102fb7a98 0x102448000 + 11991704
8   BraveCore                     	0x0000000102f8558c 0x102448000 + 11785612
9   BraveCore                     	0x0000000102f5c66c 0x102448000 + 11617900
10  BraveCore                     	0x0000000102f9cc30 0x102448000 + 11881520
11  BraveCore                     	0x00000001028307e8 0x102448000 + 4098024
12  BraveCore                     	0x0000000102f9cdac 0x102448000 + 11881900
13  BraveCore                     	0x0000000102fb3370 0x102448000 + 11973488
14  libsystem_pthread.dylib       	0x00000001d65f1ca8 0x1d65f0000 + 7336
15  libsystem_pthread.dylib       	0x00000001d65fa788 0x1d65f0000 + 42888

Thread 14 name:  ThreadPoolForegroundWorker
Thread 14:
0   libsystem_kernel.dylib        	0x00000001ba840dd0 0x1ba83d000 + 15824
1   libsystem_kernel.dylib        	0x00000001ba840184 0x1ba83d000 + 12676
2   BraveCore                     	0x0000000102fba7d8 0x102448000 + 12003288
3   BraveCore                     	0x0000000102f96a00 0x102448000 + 11856384
4   BraveCore                     	0x0000000102f97434 0x102448000 + 11858996
5   BraveCore                     	0x0000000102f97004 0x102448000 + 11857924
6   BraveCore                     	0x0000000102fb3370 0x102448000 + 11973488
7   libsystem_pthread.dylib       	0x00000001d65f1ca8 0x1d65f0000 + 7336
8   libsystem_pthread.dylib       	0x00000001d65fa788 0x1d65f0000 + 42888

Thread 15 name:  JavaScriptCore bmalloc scavenger
Thread 15:
0   libsystem_kernel.dylib        	0x00000001ba86475c 0x1ba83d000 + 161628
1   libsystem_pthread.dylib       	0x00000001d65f5550 0x1d65f0000 + 21840
2   libc++.1.dylib                	0x00000001a288ec8c 0x1a2882000 + 52364
3   JavaScriptCore                	0x00000001987580f8 0x19788e000 + 15507704
4   JavaScriptCore                	0x000000019875c698 0x19788e000 + 15525528
5   JavaScriptCore                	0x000000019875c2d4 0x19788e000 + 15524564
6   JavaScriptCore                	0x000000019875d798 0x19788e000 + 15529880
7   libsystem_pthread.dylib       	0x00000001d65f1ca8 0x1d65f0000 + 7336
8   libsystem_pthread.dylib       	0x00000001d65fa788 0x1d65f0000 + 42888

Thread 16 name:  ThreadPoolSingleThreadSharedForegroundBlocking0
Thread 16:
0   libsystem_kernel.dylib        	0x00000001ba840dd0 0x1ba83d000 + 15824
1   libsystem_kernel.dylib        	0x00000001ba840184 0x1ba83d000 + 12676
2   BraveCore                     	0x0000000102fba7d8 0x102448000 + 12003288
3   BraveCore                     	0x0000000102f96a00 0x102448000 + 11856384
4   BraveCore                     	0x0000000102f97434 0x102448000 + 11858996
5   BraveCore                     	0x0000000102f97030 0x102448000 + 11857968
6   BraveCore                     	0x0000000102fb3370 0x102448000 + 11973488
7   libsystem_pthread.dylib       	0x00000001d65f1ca8 0x1d65f0000 + 7336
8   libsystem_pthread.dylib       	0x00000001d65fa788 0x1d65f0000 + 42888

Thread 17 name:  ThreadPoolForegroundWorker
Thread 17:
0   libsystem_kernel.dylib        	0x00000001ba840dd0 0x1ba83d000 + 15824
1   libsystem_kernel.dylib        	0x00000001ba840184 0x1ba83d000 + 12676
2   BraveCore                     	0x0000000102fba7d8 0x102448000 + 12003288
3   BraveCore                     	0x0000000102f96a00 0x102448000 + 11856384
4   BraveCore                     	0x0000000102f97434 0x102448000 + 11858996
5   BraveCore                     	0x0000000102f97004 0x102448000 + 11857924
6   BraveCore                     	0x0000000102fb3370 0x102448000 + 11973488
7   libsystem_pthread.dylib       	0x00000001d65f1ca8 0x1d65f0000 + 7336
8   libsystem_pthread.dylib       	0x00000001d65fa788 0x1d65f0000 + 42888

Thread 18 name:  ThreadPoolForegroundWorker
Thread 18:
0   libsystem_kernel.dylib        	0x00000001ba840dd0 0x1ba83d000 + 15824
1   libsystem_kernel.dylib        	0x00000001ba840184 0x1ba83d000 + 12676
2   BraveCore                     	0x0000000102fba7d8 0x102448000 + 12003288
3   BraveCore                     	0x0000000102fba58c 0x102448000 + 12002700
4   BraveCore                     	0x00000001036e2670 0x102448000 + 19506800
5   BraveCore                     	0x00000001036e45d0 0x102448000 + 19514832
6   BraveCore                     	0x00000001036e3d30 0x102448000 + 19512624
7   BraveCore                     	0x00000001036eaa40 0x102448000 + 19540544
8   BraveCore                     	0x00000001036eae0c 0x102448000 + 19541516
9   BraveCore                     	0x00000001036d57b0 0x102448000 + 19453872
10  BraveCore                     	0x00000001036d54a8 0x102448000 + 19453096
11  BraveCore                     	0x00000001036e9f38 0x102448000 + 19537720
12  BraveCore                     	0x00000001036ea3d0 0x102448000 + 19538896
13  BraveCore                     	0x00000001036e83bc 0x102448000 + 19530684
14  BraveCore                     	0x00000001036e8a1c 0x102448000 + 19532316
15  BraveCore                     	0x0000000102fb3458 0x102448000 + 11973720
16  BraveCore                     	0x0000000102d11ba8 0x102448000 + 9214888
17  BraveCore                     	0x0000000102f739a4 0x102448000 + 11712932
18  BraveCore                     	0x0000000102f8fbb8 0x102448000 + 11828152
19  BraveCore                     	0x0000000102f90048 0x102448000 + 11829320
20  BraveCore                     	0x0000000102f8f960 0x102448000 + 11827552
21  BraveCore                     	0x0000000102fb2e78 0x102448000 + 11972216
22  BraveCore                     	0x0000000102f8f68c 0x102448000 + 11826828
23  BraveCore                     	0x0000000102f97364 0x102448000 + 11858788
24  BraveCore                     	0x0000000102f97004 0x102448000 + 11857924
25  BraveCore                     	0x0000000102fb3370 0x102448000 + 11973488
26  libsystem_pthread.dylib       	0x00000001d65f1ca8 0x1d65f0000 + 7336
27  libsystem_pthread.dylib       	0x00000001d65fa788 0x1d65f0000 + 42888

Thread 19:
0   libsystem_pthread.dylib       	0x00000001d65fa774 0x1d65f0000 + 42868

Thread 20:
0   libsystem_pthread.dylib       	0x00000001d65fa774 0x1d65f0000 + 42868

Thread 21:
0   libsystem_pthread.dylib       	0x00000001d65fa774 0x1d65f0000 + 42868

Thread 22:
0   libsystem_pthread.dylib       	0x00000001d65fa774 0x1d65f0000 + 42868

Thread 23 name:  AVAudioSession Notify Thread
Thread 23:
0   libsystem_kernel.dylib        	0x00000001ba840dd0 0x1ba83d000 + 15824
1   libsystem_kernel.dylib        	0x00000001ba840184 0x1ba83d000 + 12676
2   CoreFoundation                	0x000000018e67ecf8 0x18e5e1000 + 646392
3   CoreFoundation                	0x000000018e678ea8 0x18e5e1000 + 622248
4   CoreFoundation                	0x000000018e6784bc 0x18e5e1000 + 619708
5   AudioSession                  	0x0000000195f282ac 0x195f1b000 + 53932
6   AudioSession                  	0x0000000195f2a390 0x195f1b000 + 62352
7   libsystem_pthread.dylib       	0x00000001d65f1ca8 0x1d65f0000 + 7336
8   libsystem_pthread.dylib       	0x00000001d65fa788 0x1d65f0000 + 42888

Thread 24:
0   libsystem_pthread.dylib       	0x00000001d65fa774 0x1d65f0000 + 42868

Thread 25:
0   libsystem_pthread.dylib       	0x00000001d65fa774 0x1d65f0000 + 42868

Thread 26:
0   libsystem_pthread.dylib       	0x00000001d65fa774 0x1d65f0000 + 42868

Thread 27:
0   libsystem_pthread.dylib       	0x00000001d65fa774 0x1d65f0000 + 42868

Thread 28 name:  ThreadPoolForegroundWorker
Thread 28:
0   libsystem_kernel.dylib        	0x00000001ba840dd0 0x1ba83d000 + 15824
1   libsystem_kernel.dylib        	0x00000001ba840184 0x1ba83d000 + 12676
2   BraveCore                     	0x0000000102fba7d8 0x102448000 + 12003288
3   BraveCore                     	0x0000000102f96a00 0x102448000 + 11856384
4   BraveCore                     	0x0000000102f9719c 0x102448000 + 11858332
5   BraveCore                     	0x0000000102f97004 0x102448000 + 11857924
6   BraveCore                     	0x0000000102fb3370 0x102448000 + 11973488
7   libsystem_pthread.dylib       	0x00000001d65f1ca8 0x1d65f0000 + 7336
8   libsystem_pthread.dylib       	0x00000001d65fa788 0x1d65f0000 + 42888

Thread 29 name:  CacheThread_BlockFile
Thread 29:
0   libsystem_kernel.dylib        	0x00000001ba840dd0 0x1ba83d000 + 15824
1   libsystem_kernel.dylib        	0x00000001ba840184 0x1ba83d000 + 12676
2   CoreFoundation                	0x000000018e67ecf8 0x18e5e1000 + 646392
3   CoreFoundation                	0x000000018e678ea8 0x18e5e1000 + 622248
4   CoreFoundation                	0x000000018e6784bc 0x18e5e1000 + 619708
5   Foundation                    	0x000000018f8f9e30 0x18f8f2000 + 32304
6   BraveCore                     	0x0000000102fb8c74 0x102448000 + 11996276
7   BraveCore                     	0x0000000102fb7a98 0x102448000 + 11991704
8   BraveCore                     	0x0000000102f8558c 0x102448000 + 11785612
9   BraveCore                     	0x0000000102f5c66c 0x102448000 + 11617900
10  BraveCore                     	0x0000000102f9cc30 0x102448000 + 11881520
11  BraveCore                     	0x0000000102f9cdac 0x102448000 + 11881900
12  BraveCore                     	0x0000000102fb3370 0x102448000 + 11973488
13  libsystem_pthread.dylib       	0x00000001d65f1ca8 0x1d65f0000 + 7336
14  libsystem_pthread.dylib       	0x00000001d65fa788 0x1d65f0000 + 42888

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x80000001d6452bb0   x1: 0x00000002807fcf80   x2: 0x0000000000000007   x3: 0x000000019d77a0cc
    x4: 0x00000000000062dc   x5: 0x000000016f4989c0   x6: 0x000000000000002e   x7: 0x0000000000000001
    x8: 0x000000000000007f   x9: 0x0000000000000020  x10: 0x00000000000007fb  x11: 0x00000000000007fd
   x12: 0x0000000000000001  x13: 0x00000000f7809030  x14: 0x00000000f7a09800  x15: 0x0000000000000013
   x16: 0x0000000080000000  x17: 0x0000000077a00000  x18: 0x000000010ebeb93c  x19: 0x00000001d6452bc0
   x20: 0x0000000000000000  x21: 0x0000000000000000  x22: 0x0000000000000042  x23: 0x00000001d6452ba0
   x24: 0x80000001d6452bb0  x25: 0xd000000000000032  x26: 0x000000000000000b  x27: 0x0000000000000002
   x28: 0x000000016f499108   fp: 0x000000016f498b60   lr: 0x0000000192234730
    sp: 0x000000016f498ae0   pc: 0x0000000192234730 cpsr: 0x60000000
   esr: 0xf2000001  Address size fault

**Comment by iccub** [comment] 2022-02-09 14:23
thanks @dodieboy,
we are still investigating, looks like it's iOS 14.1 specific problem, 
on newer iOS 14+ versions it does not happen

It is related to us moving to use a thing called content worlds when evaluating javascript
https://developer.apple.com/documentation/webkit/wkcontentworld

**Closed as completed** 2022-02-09 15:28 UTC
Labels: bug, QA/Yes, crash, release-notes/include, QA Pass - iPhone, iOS 14

**Comment by iccub** [comment] 2022-02-09 15:50
We found a fix, this will probably land in our next builds pretty soon.
Only temporary workaround is to update your iOS version to 14.3 or higher :(

**Comment by iccub** [comment] 2022-02-09 16:59
iOS 14.1 verification **PASSED**
video proof:


https://user-images.githubusercontent.com/6950387/153245187-29d09a0d-9f6f-434a-995f-3e4236aa5783.mov

**Comment by iccub** [comment] 2022-02-14 16:30
Hi, build with this fix is live, you can update from App Store manually

**Comment by dodieboy** [comment] 2022-02-14 16:35
Great work to the brave IOS developer team, manage to push out a fix in a short time. I have downloaded it and using it with no more crashes
