### ISSUE TITLE
Search result on Qwant doesn't open in private mode

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#982] opened 2019-03-18 12:44 UTC
### Description: 
Issue reported by @johnnyryan  and  @snyderp.
Search result on Qwant doesn't open in private mode

### Steps to Reproduce 
  1. Open a private tab
  2. Visit qwant.com and search 
  3. Tap on the search result, page doesn't load 

**Actual result:** 
Search result on Qwant doesn't open in private mode

**Expected result:**
Should open the page

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.8

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? 
Yes, same result
- did you check in Safari/Firefox (WkWebView-based browsers)? 
Yes, works fine on FF

**Comment by iccub** [comment] 2019-03-18 13:56
Caused by this https://github.com/brave/brave-ios/commit/29709768c848f51d8e0baa92ea282f94d3dc365f

**Comment by kylehickinson** [comment] 2019-03-18 14:02
Duplicate of #456

**Comment by kylehickinson** [comment] 2019-03-18 14:05
Copied over priority/labels to #456. Maybe should update the original issue to be more obvious that these are duplicates

**Closed as completed** 2019-03-18 14:04 UTC
Labels: bug, closed/duplicate, priority/P1, release/blocking
