### ISSUE TITLE
Closing last privatemode tab and pressing private button at same time causes crash

### ISSUE THREAD

**Issue by Leve1** [brave/brave-ios#1346] opened 2019-08-08 08:28 UTC
### Description: 
Closing last privatemode tab and pressing private button at the same time causes crash

### Steps to Reproduce 
  1.Have only one private mode tab open
  2.Close tab and press private button at same time
  3.

**Actual result:** 
App crashes

**Expected result:**
Not to crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
v1.11(19.08.01.15)

**Device details:** 
iPhone 6s (iOS 12.1.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
BraveApp log file below (Not sure if this will help)
[browser.20190808T021743-0600.log](https://github.com/brave/brave-ios/files/3480586/browser.20190808T021743-0600.log)

**Comment by srirambv** [comment] 2019-08-08 11:14
Reproduced the issue.

**Comment by jhreis** [comment] 2019-08-09 01:38
@srirambv is this related to https://github.com/brave/brave-ios/issues/777?

**Comment by srirambv** [comment] 2019-08-09 04:06
@jhreis  no both are different. #777 has no browser crash just a weird state

**Comment by Brandon-T** [comment] 2019-08-10 00:10
I have a fix for this already in another bigger PR because I discovered something similar while debugging my previous PR.. 

But I will make a separate PR that fixes this specifically (just copying the same fix).

**Comment by iccub** [comment] 2019-08-12 15:59
Duplicate of https://github.com/brave/brave-ios/issues/1346

This should be fixed in next release

**Closed as completed by iccub** 2019-08-12 15:59 UTC
Labels: bug, closed/duplicate, QA/Yes, crash, release-notes/include
