### ISSUE TITLE
Ads cause slowdown before appearing on IOS

### ISSUE THREAD

**Issue by JamaicanSkeleton** [brave/brave-ios#3992] opened 2021-07-31 21:01 UTC
## Description 

When an ad appears as a notification on IOS, the app freezes or slows down for a few seconds before the ad appears.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Expected result:
No slow down or freezing before in-browser ad notifications.

## Reproduces how often: 
Every in-browser ad notification

## Version/Channel Information:
Version 1.28 (21.7.9.13)

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by iccub** [comment] 2021-08-02 14:43
I will leave this ticket open but it is most likely same as https://github.com/brave/brave-ios/issues/3941, we are still investigating the problem.

**Comment by JamaicanSkeleton** [comment] 2021-08-02 15:55
Ok. Thank you and the rest of the team at Brave for your guys' work.

**Comment by iccub** [comment] 2021-09-29 09:14
we have a fix coming soon, for now, closing this as a duplicate of https://github.com/brave/brave-ios/issues/3941

**Closed as completed by iccub** 2021-09-29 09:14 UTC
Labels: closed/duplicate
