### ISSUE TITLE
Haptic Touch Support, Please.

### ISSUE THREAD

**Issue by Victorio115** [brave/brave-ios#1800] opened 2019-10-26 02:51 UTC
### Description: 
Haptic Touch is a function which consist of show a preview of an element, when that one is touched and the touch is held for a few seconds, or is touched and applying pressure in the process.  
  
That function isn't supported on this version of Brave.

### Steps to Reproduce 
  1. Go to an any element on a website (Such as a link, or a picture).
  2. Touch that element and hold for a few seconds.
  3. Tap the "Cancel" option in the menu that has appeared on the screen.
  4. Touch the same element, but apply some pressure.
  5. Tap the "Cancel" option in the menu that has appeared on the screen.

**Actual result:**  
![VideoToGif_GIF 2](https://user-images.githubusercontent.com/50971728/67613248-39ca6f80-f760-11e9-92aa-a2faa25819db.GIF)

**Expected result:**  
![VideoToGif_GIF](https://user-images.githubusercontent.com/50971728/67613236-1ef7fb00-f760-11e9-823b-911468dda3a1.GIF)
![VideoToGif_GIF 3](https://user-images.githubusercontent.com/50971728/67613253-4a7ae580-f760-11e9-87b6-eb87cf4b7024.GIF)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced.

**Brave Version:** 
Version 1.12.1 (19.09.20.23)

**Device details:** 
iPhone X (iOS 13.1)

**Website problems only:**
- Did you check with Brave Shields down? Brave shields are irrelevant for this issue.
- Did you check in Safari/Firefox (WkWebView-based browsers)? Look the **Expected Result**.

### Additional Information
N/A

**Comment by iccub** [comment] 2019-10-26 08:42
This is fixed and will be available in 1.13 release which is few weeks from now :)

Closing as duplicate of https://github.com/brave/brave-ios/issues/1499

**Closed as completed by iccub** 2019-10-26 08:42 UTC
Labels: closed/duplicate
