### ISSUE TITLE
Share with Brave

### ISSUE THREAD

**Issue by chkk525** [brave/brave-ios#2994] opened 2020-10-28 02:36 UTC
Please search for the spec "Increase our social virality" > Share with Brave section for details

GitHub Issue Android: https://github.com/brave/brave-browser/issues/12352

**Comment by kylehickinson** [comment] 2020-11-23 20:45
@anthonypkeane We do not have access to this spec in Drive

**Comment by kylehickinson** [comment] 2020-11-23 20:48
Duplicate of https://github.com/brave/brave-ios/issues/2981

**Closed as completed by kylehickinson** 2020-11-23 20:48 UTC
Labels: closed/duplicate
