### ISSUE TITLE
[Follow up to 5636] No animation on peeking news card initially

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#6938] opened 2023-02-13 21:12 UTC
### Description: 
Peeking news card animation does not work when landing on NTP on first launch 

Follow up to https://github.com/brave/brave-ios/issues/5636

### Steps to Reproduce 
  1. Install 1.48.x
  2. Observe peeking news card on NTP
  3. Pull to refresh (to fix animation)

### Actual result: 
Animation does not work 

https://user-images.githubusercontent.com/17885425/218575357-bbeb39ac-1f2e-4dc0-a19e-dcecff50a1d1.MP4

### Expected result:
Animation should work 

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

### Brave Version: 
`1.48 (23.2.10.14)`

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
iPad, iPhone
iOS 16, 15

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment] 2023-02-13 21:43
Duplicate of https://github.com/brave/brave-ios/issues/6787

**Closed as not planned by kylehickinson** 2023-02-13 21:43 UTC
Labels: closed/duplicate
