### ISSUE TITLE
[Playlist] - Crash when deleting cache via Privacy Settings

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#3586] opened 2021-04-27 17:11 UTC
### Description: 
Playlist crashes when deleting cache via the privacy settings

### Steps to Reproduce 
  1. Go to Shields Privacy
  2. Enable both playlist options
  3. Clear Data Now
  4. Experience Crash

**Actual result:** 
Crashes

**Expected result:**
Shouldn't Crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent Issue.

**Comment by iccub** [comment] 2021-04-27 17:13
duplicate of https://github.com/brave/brave-ios/issues/3586

**Closed as completed by iccub** 2021-04-27 17:13 UTC
Labels: closed/duplicate
