### ISSUE TITLE
Brave sync is not working on iOS: 1.37

### ISSUE THREAD

**Issue by bhaskarnn9** [brave/brave-ios#5304] opened 2022-04-28 21:51 UTC
### Description: 
Brave sync is not working on iOS: 1.37

### Steps to Reproduce 
  1. Navigate to settings > Sync > I have a Sync code on iOS
  2. enter sync phrase/qr code from the laptop

**Actual result:** 
Sync Communication Error
The Sync Agent is currently offline or not reachable. Please try again later.
Attached screenshot

**Expected result:**
Sync successful

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always 5/5

**Brave Version:** 
1.37

**Device details:** 
15.4.1

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by bhaskarnn9** [comment] 2022-04-29 03:26
![IMG_2313](https://user-images.githubusercontent.com/28062775/165881030-713cdb67-87aa-4ec0-9e78-0437896cc592.jpg)

**Comment by bhaskarnn9** [comment] 2022-05-02 15:22
Just a friendly follow up! Any update on this?

**Comment by Brandon-T** [comment] 2022-05-12 16:48
Hi, I was not able to reproduce this issue. The error above shows up when the device fails to join the chain for any reason.
Are you joining Brave-iOS from the Appstore to Brave-Nightly or Beta? OR is it the release versions you are joining to the sync chain?

**Comment by bhaskarnn9** [comment] 2022-05-12 17:08
I’m trying to join sync chain on MAC OS (Brave stable) from iOS and I’m unable to.

Just tried and issue persists

Sent from my iPhone

On May 12, 2022, at 11:48, Brandon-T ***@***.***> wrote:

﻿

Hi, I was not able to reproduce this issue. The error above shows up when the device fails to join the chain for any reason.
Are you joining Brave-iOS from the Appstore to Brave-Nightly or Beta? OR is it the release versions you are joining to the sync chain?

**Comment by iccub** [comment] 2022-05-16 14:28
@bhaskarnn9 can you post the screenshot of your sync-internals?
Go to sync settings and tap on the cogwheel icon in top right

**Comment by bhaskarnn9** [comment] 2022-05-18 03:58
![IMG_2480](https://user-images.githubusercontent.com/28062775/168954283-165bb027-d0e5-4975-8fa8-955abd828fee.jpg)
@iccub here. Thank you

Full error(since screen shot is unable to capture everything):

Model Type	Total Entries	Live Entries	Message	State
Bookmarks	0	0	Error: GenerateCryptoErrorsForTypes@components/sync/driver/data_type_manager_impl.cc:35, cryptographer error was encountered:	Not Running
Preferences	0	0		Not Running
Passwords	0	0		Not Running
Autofill Profiles	0	0		Not Running
Autofill Wallet	0	0		Not Running
Autofill Wallet Metadata	0	0		Not Running
Autofill Wallet Offer	0	0		Not Running
Typed URLs	0	0		Not Running
History Delete Directives	0	0		Not Running
Device Info	0	0	Error: GenerateCryptoErrorsForTypes@components/sync/driver/data_type_manager_impl.cc:35, cryptographer error was encountered:	Not Running
Priority Preferences	0	0		Not Running
User Events	0	0	Datatype preconditions not met.	Not Running
Send Tab To Self	0	0

**Comment by AlexeyBarabash** [comment] 2022-05-19 15:07
Hello @bhaskarnn9 ,

The work on this issue is currently in progress, details at https://github.com/brave/brave-browser/issues/22898 . Will be fixed soon.

**Comment by bhaskarnn9** [comment] 2022-05-31 23:13
@iccub Since [milestone/290](https://github.com/brave/brave-browser/milestone/290) is not blocked by iOS issues, can we expect a fix sooner on iOS? TIA

**Comment by iccub** [comment] 2022-06-01 09:51
We rely on this code @bhaskarnn9, fastest we can deliver it would be in 1.40 after this code is uplifted cc @AlexeyBarabash

**Comment by AlexeyBarabash** [comment] 2022-06-01 09:53
@iccub 
sure, let me uplift

**Comment by AlexeyBarabash** [comment] 2022-06-01 10:01
- 1.40.x https://github.com/brave/brave-core/pull/13556
- 1.39.x https://github.com/brave/brave-core/pull/13557

**Comment by iccub** [comment] 2022-06-13 15:47
Should be resolved in version 1.40

**Closed as completed by iccub** 2022-06-13 15:47 UTC
Labels: bug, QA Pass - iPhone X, QA/Yes, QA Pass - iPhone, QA Pass - iPad

**Comment by bhaskarnn9** [comment] 2022-06-13 15:55
Thanks a lot.

**Comment by Uni-verse** [comment] 2022-06-21 23:27
Verification completed using version ` 1.40 (22.6.21.16)`

Devices: iPhone 12 | iOS 15.4, iPhone X | iOS 14.4.2 | iPad (7th Gen) | iOS 15.5

- Confirmed able to join sync chain generated from Desktop (MacOS) by scanning and entering code words.
- Confirmed able to join by scanning old and new QR codes from iOS.
- Confirmed able to join sync chain created on other iOS devices.

<img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/174912853-7d7171a0-7227-4d38-ad77-012993763118.PNG">
