### ISSUE TITLE
Search Engine Favicons doesn't respect theme

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3433] opened 2021-03-18 11:53 UTC
### Description: 
Search Engine Favicons doesn't respect theme

### Steps to Reproduce 
  1. Add YT & WIki as custom search engines
  2. Switch theme
  3. Favicons doesnt respect browser themes

**Actual result:** 

![image](https://user-images.githubusercontent.com/17010094/111621843-5bf2e080-87e0-11eb-84a6-a38c2cfa56c6.png) | ![image](https://user-images.githubusercontent.com/17010094/111621857-5e553a80-87e0-11eb-9e4c-17b4f346b7a6.png)
-- | --

**Expected result:**
Should show similar to other quick search engine icons

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.24

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc: @soner-yuksel

**Comment by soner-yuksel** [comment] 2021-03-19 17:30
The particular solution in the Pr is not working as expected, closing this PR and bumping the ticket to 1.25 for better generalized solution.

**Comment by michalnowak061** [comment] 2021-08-22 16:38
Is this still a problem? I can't reproduce this in Simulator.

<img src="https://user-images.githubusercontent.com/47181362/130361941-7fe7b4e4-3450-4512-8b35-7b7edf4501da.png" width="45%" height="45%"> <img src="https://user-images.githubusercontent.com/47181362/130361944-58b81131-5be3-4a00-8665-427566c6524f.png" width="45%" height="45%">

**Comment by iccub** [comment] 2023-02-07 18:10
closing in favor of https://github.com/brave/brave-ios/issues/6066

**Closed as not planned by iccub** 2023-02-07 18:10 UTC
Labels: closed/invalid
