### ISSUE TITLE
Add support for server/geo selection

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3267] opened 2021-02-05 00:34 UTC
### Description: 

Please see GDrive "Brave VPN on iOS - V2" for more info.

Add support for server/geo selection

Please upload final screenshots here once dev completed to aid QA

**Comment by anthonypkeane** [comment] 2021-04-07 17:03
@iccub can we close this out now?

**Comment by iccub** [comment] 2021-04-07 17:48
Yes, closing as duplicate of https://github.com/brave/brave-ios/issues/2934

**Closed as completed by iccub** 2021-04-07 17:48 UTC
Labels: closed/duplicate
