### ISSUE TITLE
Save password prompt isn't displayed

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#2052] opened 2019-11-28 16:52 UTC
### Description: 

Save password prompt isn't displayed
### Steps to Reproduce 
  1. Clean profile 1.14
  2. Open Twitter.com and Gmail.com
  3. Login using valid credentials
  4. Save password prompt isn't displayed

**Actual result:** 

Save password prompt isn't displayed
**Expected result:**
Save password prompt should be displayed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
1.14 and 1.13

**Device details:** 

iPhone 8
**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @brave/legacy_qa @jhreis

**Comment by iccub** [comment] 2019-11-29 13:44
Can you try on 19.11.27.22?

**Comment by kjozwiak** [comment] 2020-02-17 10:34
@GeetaSarvadnya mind quickly checking this to see if it's been fixed one of the releases after ~November? If it's working, let's close this off.

**Comment by GeetaSarvadnya** [comment] 2020-02-17 10:48
@kjozwiak Verified issue in release and dev channels. The issue still persists in `1.14.3 (20.02.03.23) ` release version and `Dev 1.15 (20.02.12.10)`

**Comment by kjozwiak** [comment] 2020-02-17 10:51
Thanks for checking @GeetaSarvadnya 👍Quickly checked as well using `1.4.3 (20.02.01.06)` and I'm seeing the same problem on Twitter. @iccub looks like this is still a problem.

**Comment by kjozwiak** [comment] 2021-05-25 20:56
BTW, this is still happening as @GeetaSarvadnya ran into it while she was running through the manual passes for the `1.25.1` HF release.

**Comment by LaurenWags** [comment] 2021-06-15 18:09
Reproduced on `1.26 (21.5.28.14)` from app store and `1.27 (21.6.15.14)` from Dev TF. Used ravelry.com as the site.

**Comment by iccub** [comment] 2021-09-08 12:58
closing in favor of https://github.com/brave/brave-ios/issues/4112

**Closed as completed by iccub** 2021-09-08 12:58 UTC
Labels: closed/duplicate
