### ISSUE TITLE
Scribble not working properly on iPadOS

### ISSUE THREAD

**Issue by StephanKonig** [brave/brave-ios#3715] opened 2021-05-17 19:56 UTC
## Description 
Scribble not working properly on iPadOS

## Steps to Reproduce

   1.  Open Brave Browser
   2. Try to scribble in the address bar

## Actual result:
You cannot see what you scribbled in the address bar. However, your scribble is recognized and converted to computer text.

## Expected result:

You should see what you scribble
## Reproduces how often: 
Easily reproduced

## Brave version (info found on brave://version)
iPad OS 14.6 (18F71), Brave Browser 1.25

## Version/Channel Information:

- Can you reproduce this issue with the current release? YES
- Can you reproduce this issue with the beta channel? Not tested
- Can you reproduce this issue with the dev channel? Not tested
- Can you reproduce this issue with the nightly channel? Not tested

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Not tested

**Comment by AyushChatto** [comment] 2021-05-25 13:08
Hi it seems that the issue is only caused in the dark mode, as the scribble is also in black. I'm new to Swift but I'd like to work on this issue if possible.

**Comment by kylehickinson** [comment] 2021-05-25 13:54
Duplicate of #3319

**Comment by kylehickinson** [comment] 2021-05-25 13:55
@AyushChatto if you would like to investigate/work on this please continue with #3319 instead :)

**Closed as completed by kylehickinson** 2021-05-25 13:54 UTC
Labels: closed/duplicate

**Comment by AyushChatto** [comment] 2021-05-25 16:44
@kylehickinson thanks for the heads up, looking into it!
