### ISSUE TITLE
Add blocking quality difference desktop versus iOS

### ISSUE THREAD

**Issue by phoogm** [brave/brave-ios#3452] opened 2021-03-23 16:00 UTC
### Description: 
Comparing the quality and effectiveness of add blocking for Brave on iOS and Brave on macOS there is a big and noticeable difference. Specifically cosmetic filtering does not seem to be effective on iOS where either gray areas or grey bars in between content appear. It could be due to iOS limitations for list / items limitation, but comparing to e.g. AdGuard for iOS who uses multiple content blockers it seems to be able to get desktop class parity in ad-blocking and cosmetic filtering. If it is not possible to upgrade the effectiveness from within the iOS version of the Brave Browser, then would it be possible to build a Brave add blocking companion (separate app) that acts as multiple content blockers and works together with the iOS Brave Browser? That possibly would allow e.g. a standard blocking (only Brave browser) and aggressive (Brave browser plus companion) setting from within the Brave browser.

### Steps to Reproduce 
  1. Open the 9to5Mac site in Brave on iOS and observe the grey bars in-between the articles
  2. Open the 9to5Mac site in Brave for macOS and observe the gray bars are not visible
  3. Comparing the two results Brave on iOS does not show the same quality.

**Actual result:** 
![Screenshot 2021-03-23 at 16 53 14](https://user-images.githubusercontent.com/56597375/112176965-d5cc0500-8bf8-11eb-90dd-fa8d6ee011b0.png)

**Expected result:**
<img width="1703" alt="2021-03-23_16-55-44" src="https://user-images.githubusercontent.com/56597375/112177003-e0869a00-8bf8-11eb-9629-9605f4de6d28.png">

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
Version 1.23.1 (21.2.24.16)

**Device details:** 
iPad Pro (12.9-inch) (3rd generation)

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? Firefox has the same kind of issues, but also Edge on iOS using adblock.

### Additional Information
Thanks for looking into,

Best regards.

**Comment by bsclifton** [comment] 2021-03-24 19:10
We do use a reduced set of rules (due to size) in a data set we call "SlimList". I'm not sure if there is any information publicly about this - but basically Adblock Plus rules are converted over to the Content Blocker format that iOS expects. I am pretty sure cosmetic filters are not used though - which may clean up those areas you noticed

cc: @pes10k and @kylehickinson for additional comment

**Comment by iccub** [comment] 2021-03-24 19:38
blank space is usually our lack of cosmetic filters afaik, 
ad blocking works but we have no code to remove blank spaces

**Comment by bsclifton** [comment] 2021-05-05 05:38
Closing this as a duplicate of https://github.com/brave/brave-ios/issues/2683

**Closed as completed by bsclifton** 2021-05-05 05:38 UTC
Labels: closed/duplicate, feature/shields/adblock
