### ISSUE TITLE
crash when opening/scrolling through particular PDF

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3886] opened 2021-07-05 21:05 UTC
### Description: 

Originally reported by @pes10k via Slack, Brave will crash when loading and scrolling through the following PDF:

https://static1.squarespace.com/static/57338e2c04426238cff175c6/t/60c9462f924a473dc95dc850/1623803439283/ListaDeVinos...pdf

### Steps to Reproduce

  1. open the PDF mentioned above
  2. once loaded, start scrolling and you'll eventually crash the Brave

**Actual result:** 

Brave crashes when you open the above PDF and either leave it opened for a few seconds or start scrolling through the PDF.

**Expected result:**

Brave shouldn't be crashing.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases mentioned above.

**Brave Version:** 

* `1.27.1 (21.6.22.16)` - **Reproduced**
* `1.28 (21.7.5.14)` - **Reproduced**

**Device details:** 

* `iPhone 11` running `iOS 14.6` - **Reproduced**

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

**Comment by kylehickinson** [comment] 2021-07-05 21:21
Duplicate of https://github.com/brave/brave-ios/issues/3868

**Closed as completed by kylehickinson** 2021-07-05 21:21 UTC
Labels: closed/duplicate
