### ISSUE TITLE
region check isn't working and all regions receiving SNTP images

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2258] opened 2020-01-29 09:00 UTC
### Description: 

Sponsored images are being downloaded/used despite being in regions that shouldn't be getting those images. Example:

* `Region: India` & `Language: English` --> downloading/using SNTP images
* `Region: Canada` & `Language: English` --> downloading/using SNTP images

@GeetaSarvadnya also reproduced this issue using `Region: India` & `Language: English` as mentioned above.

Some more context can be found via the following Slack thread:

* https://bravesoftware.slack.com/archives/CQGTGBNH1/p1580280305471800

### Steps to Reproduce

**Prerequisite:**

Ensure that you have `Region: India` `Language: English` or `Region: Canada` & `Language: English` set via the iOS settings

  1. download & launch `1.14.3 (20.1.28.18)`
  2. enable rewards/ads via the initial onboarding
  3. start cycling through SNTP and you'll notice sponsored images

**Actual result:** 

Even though the regions are set to `India` or `Canada`, SNTP images are being downloaded

**Expected result:**

Certain regions shouldn't be getting SNTP images.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* Using `1.14.3 (20.1.28.18)`

**Device details:** 

* `iPhone 11` running `iOS 13.3` - **Reproduced**
* `iPad 3rd Gen` running `iOS 13.3` - **Reproduced**
* `iPhone 6s+` running `iOS 12.4.1` - **Reproduced**
* `iPad Mini 4` running `iOS 12.4.1` - **Reproduced**

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @jhreis @jsecretan @bsclifton @srirambv @anthonypkeane @Brandon-T

**Comment by iccub** [comment] 2020-01-29 09:03
duplicate of https://github.com/brave/brave-ios/issues/2257

**Closed as completed by iccub** 2020-01-29 09:03 UTC
Labels: closed/duplicate

**Comment by bsclifton** [comment] 2020-01-29 09:04
@iccub did you mean another issue? (I think it was copy/paste error 😄2258 is this one)

**Comment by iccub** [comment] 2020-01-29 09:22
Good eye @bsclifton :D changed it
