### ISSUE TITLE
Text is not visible when editing a favourite/bookmark in dark mode

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2644] opened 2020-06-18 14:09 UTC
### Description: 
Text is not visible when editing a favourite/bookmark on iPad in dark mode

### Steps to Reproduce 
  1. Install 1.18
  2. Open a new tab and edit the favourite/bookmark
  3. Text is not visible

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/85030226-d1227e00-b19a-11ea-88ca-e5b6106fa53c.png)

**Expected result:**
Should be visible 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.18(20.06.16.08)

**Device details:** 
iPad (iOS 12) - Yes
iPhone 6 (iOS 12) - Yes
iPhone XR(iOS 13.5) - No
iPhone 7+(iOS 13.5.1) - No
iPad Pro (iOS 13) - No

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

**Comment by kylehickinson** [comment] 2020-06-18 14:23
@srirambv Is this a regression or just a bug? You marked it as 1.18 milestone, is this a release blocker then?

**Comment by srirambv** [comment] 2020-06-18 15:17
Actually this is not a regression. Seems to be there on current release as well so will move it out of milestone

**Closed as completed** 2020-11-13 14:59 UTC
Labels: bug, QA/Yes, release-notes/include, QA Pass - iPhone, QA Pass - iPad, Epic: Bookmarks/Favourites, Epic: UI/Theme

**Comment by kjozwiak** [comment] 2021-02-02 06:33
Verification **PASSED** on `iPad Air (3rd Gen)` on `iOS 14.3` using the following build:

```
1.23 (21.1.28.17)
```

**`Normal Tab`** | **`Private Tab`**
-------------------|------------------
![IMG_0181](https://user-images.githubusercontent.com/2602313/106560745-84a36d00-64f5-11eb-9073-fa1799f81fc4.png) | ![IMG_0182](https://user-images.githubusercontent.com/2602313/106560755-88cf8a80-64f5-11eb-86bf-e4df1d8810ae.png)

Verification **PASSED** on `iPad Mini 4` on `iOS 13.7` using the following build:

```
1.23 (21.1.28.17)
```

**`Normal Tab`** | **`Private Tab`**
-------------------|------------------
![IMG_0433](https://user-images.githubusercontent.com/2602313/106561052-03000f00-64f6-11eb-8902-21c29f59be2c.png) | ![IMG_0434](https://user-images.githubusercontent.com/2602313/106561058-06939600-64f6-11eb-9224-5933d30a2f17.png)

Verification **PASSED** on `iPhone 11` on `iOS 14.4` using the following build:

```
1.23 (21.1.28.17)
```

**`Normal Tab`** | **`Private Tab`**
-------------------|------------------
![IMG_3521](https://user-images.githubusercontent.com/2602313/106561091-157a4880-64f6-11eb-93e8-c4a7163997bd.png) | ![IMG_3522](https://user-images.githubusercontent.com/2602313/106561098-190dcf80-64f6-11eb-9efe-0af24e358639.png)

Verification **PASSED** on `iPhone 6+` on `iOS 12.4.1` using the following build:

```
1.23 (21.1.28.17)
```

**`Normal Tab`** | **`Private Tab`**
-------------------|------------------
![IMG_0092](https://user-images.githubusercontent.com/2602313/106561403-9c2f2580-64f6-11eb-8e07-b95a83681736.png) | ![IMG_0093](https://user-images.githubusercontent.com/2602313/106561428-a4876080-64f6-11eb-9351-cbec0e1e6566.png)

**Comment by kjozwiak** [comment] 2021-02-02 06:41
@iccub @soner-yuksel looks like this still hasn't been fixed. Text still appears really light when editing bookmarks/favourites. Created https://github.com/brave/brave-ios/issues/3250 as this one already has a PR associated with it. Also adding the `release-notes/include` as this fixes an issue that's already in release.

**Comment by soner-yuksel** [comment] 2021-02-02 17:21
@kjozwiak  So what you find is a very edge case that only happens in **private mode** in iOS 12. I found a rare hack for this. Will open a PR soon which will be attached to this ticket.
